BD: "Bangladesh"
BE: "Belgique"
BF: "Burkina Faso"
BG: "Bulgarie"
BA: "Bosnie Herzégovine"
BN: "Brunei"
BO: "Bolivie"
JP: "Japon"
BI: "Burundi"
BJ: "Bénin"
BT: "Bhoutan"
JM: "Jamaïque"
BW: "Botswana"
BR: "Brésil"
BS: "Bahamas"
BY: "Bélarus"
BZ: "Belize"
RU: "Russie"
RW: "Rwanda"
RS: "Serbie"
TL: "Timor Oriental"
TM: "Turkménistan"
TJ: "Tadjikistan"
RO: "Roumanie"
GW: "Guinea-Bissau"
GT: "Guatémala"
GR: "Grèce"
GQ: "Guinée-Equatoriale"
GY: "Guyana"
GE: "Géorgie"
GB: "Royaume-Uni"
GA: "Gabon"
GN: "Guinée" 
GM: "Gambie"
GL: "Groenland"
GH: "Ghana"
OM: "Oman"
TN: "Tunisie"
JO: "Jordanie"
HR: "Croatie"
HT: "Haïti"
HU: "Hongrie"
HN: "Honduras"
PR: "Porto Rico"
PS: "Palestine"
PT: "Portugal"
PY: "Paraguay"
PA: "Panama"
PG: "Papouasie-Nouvelle-Guinée"
PE: "Pérou"
PK: "Pakistan"
PH: "Philippines"
PL: "Pologne"
ZM: "Zambie"
EH: "Sahara Occidentale"
EE: "Estonie"
EG: "Egypte"
ZA: "Afrique du Sud"
EC: "Equateur"
IT: "Italie"
VN: "Vietnam"
SB: "îles Salomon"
ET: "Ethiopie"
SO: "Somalie"
ZW: "Zimbabwe"
ES: "Espagne"
ER: "Erythrée"
ME: "Monténégro"
MD: "Moldavie"
MG: "Madagascar"
MA: "Maroc"
UZ: "Ouzbékistan"
MM: "Myanmar"
ML: "Mali"
MN: "Mongolie"
MK: "Macédoine"
MW: "Malawi"
MR: "Mauritanie"
UG: "Ouganda"
MY: "Malaysie"
MX: "Mexique"
IL: "Israël"
FR: "France"
XS: "Somaliland"
FI: "Finlande"
FJ: "Fidji"
FK: "îles Falkland"
NI: "Nicaragua"
NL: "Pays-Bas"
NO: "Norvège"
NA: "Namibie"
VU: "Vanuatu"
NC: "Nouvelle Calédonie"
NE: "Niger"
NG: "Nigeria"
NZ: "Nouvelle Zélande"
NP: "Népal"
XK: "Kosovo"
CI: "Côte d'Ivoire"
CH: "Suisse"
CO: "Colombie"
CN: "Chine"
CM: "Cameroun"
CL: "Chili"
XC: "Chypre du Nord"
CA: "Canada"
CG: "Congo"
CF: "République Centrafricaine"
CD: "République Démocratique du Congo "
CZ: "République Tchèque"
CY: "Chypre"
CR: "Costa Rica"
CU: "Cuba"
SZ: "Swaziland"
SY: "Syrie"
KG: "Kirghizistan"
KE: "Kenya"
SS: "Soudan du sud"
SR: "Suriname"
KH: "Cambodge"
SV: "Salvador"
SK: "Slovaquie"
KR: "Corée du Sud"
SI: "Slovénie"
KP: "Corée du Nord"
KW: "Koweït"
SN: "Sénégal"
SL: "Sierra Leone"
KZ: "Kazakhstan"
SA: "Arabie Saoudite"
SE: "Suède"
SD: "Soudan"
DO: "République Dominicaine"
DJ: "Djibouti"
DK: "Danemark"
DE: "Allemagne"
YE: "Yémen"
DZ: "Algérie"
US: "Etats-Unis"
UY: "Uruguay"
LB: "Liban"
LA: "Laos"
TW: "Taïwan"
TT: "Trinité et Tobago"
TR: "Turquie"
LK: "Sri Lanka"
LV: "Lettonie"
LT: "Lituanie"
LU: "Luxembourg"
LR: "Liberia"
LS: "Lesotho"
TH: "Thaïlande"
TF: "Terres australes françaises"
TG: "Togo"
TD: "Tchad"
LY: "Libye"
AE: "Emirats Arabes Unis"
VE: "Vénézuela"
AF: "Afghanistan"
IQ: "Iraq"
IS: "Islande"
IR: "Iran"
AM: "Arménie"
AL: "Albanie"
AO: "Angola"
AR: "Argentine"
AU: "Australie"
AT: "Autriche"
IN: "Inde"
TZ: "Tanzanie"
AZ: "Azerbaïdjan"
IE: "Irlande"
ID: "Indonésie"
UA: "Ukraine"
QA: "Qatar"
MZ: "Mozambique"

