jQuery(function(){
  var $ = jQuery;

  countryMapping = {
 	BD: "Bangladesh",
	BE: "Belgique",
  BF: "Burkina Faso",
  BG: "Bulgarie",
  BA: "Bosnie Herzégovine",
  BN: "Brunei",
  BO: "Bolivie",
  JP: "Japon",
  BI: "Burundi",
  BJ: "Bénin",
  BT: "Bhoutan",
  JM: "Jamaïque",
  BW: "Botswana",
  BR: "Brésil",
  BS: "Bahamas",
  BY: "Bélarus",
  BZ: "Belize",
  RU: "Russie",
  RW: "Rwanda",
  RS: "Serbie",
  TL: "Timor Oriental",
  TM: "Turkménistan",
  TJ: "Tadjikistan",
  RO: "Roumanie",
  GW: "Guinea-Bissau",
  GT: "Guatémala",
  GR: "Grèce",
  GQ: "Guinée-Equatoriale",
  GY: "Guyana",
  GE: "Géorgie",
  GB: "Royaume-Uni",
  GA: "Gabon",
  GN: "Guinée", 
  GM: "Gambie",
  GL: "Groenland",
  GH: "Ghana",
  OM: "Oman",
  TN: "Tunisie",
  JO: "Jordanie",
  HR: "Croatie",
  HT: "Haïti",
  HU: "Hongrie",
  HN: "Honduras",
  PR: "Porto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PY: "Paraguay",
  PA: "Panama",
  PG: "Papouasie-Nouvelle-Guinée",
  PE: "Pérou",
  PK: "Pakistan",
  PH: "Philippines",
  PL: "Pologne",
  ZM: "Zambie",
  EH: "Sahara Occidentale",
  EE: "Estonie",
  EG: "Egypte",
  ZA: "Afrique du Sud",
  EC: "Equateur",
  IT: "Italie",
  VN: "Vietnam",
  SB: "îles Salomon",
  ET: "Ethiopie",
  SO: "Somalie",
  ZW: "Zimbabwe",
  ES: "Espagne",
  ER: "Erythrée",
  ME: "Monténégro",
  MD: "Moldavie",
  MG: "Madagascar",
  MA: "Maroc",
  UZ: "Ouzbékistan",
  MM: "Myanmar",
  ML: "Mali",
  MN: "Mongolie",
  MK: "Macédoine",
  MW: "Malawi",
  MR: "Mauritanie",
  UG: "Ouganda",
  MY: "Malaysie",
  MX: "Mexique",
  IL: "Israël",
  FR: "France",
  XS: "Somaliland",
  FI: "Finlande",
  FJ: "Fidji",
  FK: "îles Falkland",
  NI: "Nicaragua",
  NL: "Pays-Bas",
  NO: "Norvège",
  NA: "Namibie",
  VU: "Vanuatu",
  NC: "Nouvelle Calédonie",
  NE: "Niger",
  NG: "Nigeria",
  NZ: "Nouvelle Zélande",
  NP: "Népal",
  XK: "Kosovo",
  CI: "Côte d'Ivoire",
  CH: "Suisse",
  CO: "Colombie",
  CN: "Chine",
  CM: "Cameroun",
  CL: "Chili",
  XC: "Chypre du Nord",
  CA: "Canada",
  CG: "Congo",
  CF: "République Centrafricaine",
  CD: "République Démocratique du Congo",
  CZ: "République Tchèque",
  CY: "Chypre",
  CR: "Costa Rica",
  CU: "Cuba",
  SZ: "Swaziland",
  SY: "Syrie",
  KG: "Kirghizistan",
  KE: "Kenya",
  SS: "Soudan du sud",
  SR: "Suriname",
  KH: "Cambodge",
  SV: "Salvador",
  SK: "Slovaquie",
  KR: "Corée du Sud",
  SI: "Slovénie",
  KP: "Corée du Nord",
  KW: "Koweït",
  SN: "Sénégal",
  SL: "Sierra Leone",
  KZ: "Kazakhstan",
  SA: "Arabie Saoudite",
  SE: "Suède",
  SD: "Soudan",
  DO: "République Dominicaine",
  DJ: "Djibouti",
  DK: "Danemark",
  DE: "Allemagne",
  YE: "Yémen",
  DZ: "Algérie",
  US: "Etats-Unis",
  UY: "Uruguay",
  LB: "Liban",
  LA: "Laos",
  TW: "Taïwan",
  TT: "Trinité et Tobago",
  TR: "Turquie",
  LK: "Sri Lanka",
  LV: "Lettonie",
  LT: "Lituanie",
  LU: "Luxembourg",
  LR: "Liberia",
  LS: "Lesotho",
  TH: "Thaïlande",
  TF: "Terres australes françaises",
  TG: "Togo",
  TD: "Tchad",
  LY: "Libye",
  AE: "Emirats Arabes Unis",
  VE: "Vénézuela",
  AF: "Afghanistan",
  IQ: "Iraq",
  IS: "Islande",
  IR: "Iran",
  AM: "Arménie",
  AL: "Albanie",
  AO: "Angola",
  AR: "Argentine",
  AU: "Australie",
  AT: "Autriche",
  IN: "Inde",
  TZ: "Tanzanie",
  AZ: "Azerbaïdjan",
  IE: "Irlande",
  ID: "Indonésie",
  UA: "Ukraine",
  QA: "Qatar",
  MZ: "Mozambique"
  }

    $('#focus-africa').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['DZ', 'ZA'], animate: true});
    });
    $('#focus-amenord').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['CA', 'MX'], animate: true});
    });
    $('#focus-amecentral').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['MX', 'PA'], animate: true});
    });
    $('#focus-amesud').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['CO', 'FK'], animate: true});
    });
    $('#focus-europe').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['ES', 'SE'], animate: true});
    });
    $('#focus-asie').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['KZ', 'KH', 'JP', 'ID'], animate: true});
    });
    $('#focus-oceanie').click(function(){
      $('#map1').vectorMap('set', 'focus', {regions: ['AU', 'NZ'], animate: true});
    });
  $('#focus-init').click(function(){
      $('#map1').vectorMap('set', 'focus', {scale: 1, x: 0.5, y: 0.5, animate: true});
  });

     $('#map1').vectorMap({
    map: 'world_mill_en',
    panOnDrag: true,
    focusOn: {
      x: 0.5,
      y: 0.5,
      scale: 2,
      animate: true
    },
    onRegionClick: function(e, code, isSelected, selectedRegions) {
      var url = "http://130.104.253.12:8080/resultatPays/" + countryMapping[code];
      console.log(url);
      document.location.href = url;
     
    },
    series: {
      regions: [
      {
        scale: ['#F9987B', '#EC1E32','#F9423A', '#E03C31', '#FF5C39', '#F95D62', '#FF8200', '#FF671F', '#FA4616', '#EC1E32', '#FF7F41', '#F9423A','#8f3237', '#E03C31', '#FF5C39', '#F95D62', '#F9987B'],
        normalizeFunction: 'polynomial',
        values: {
          "AF": 16.63,
          "AL": 11.58,
          "DZ": 158.97,
          "AO": 85.81,
          "AG": 1.1,
          "AR": 351.02,
          "AM": 8.83,
          "AU": 1219.72,
          "AT": 366.26,
          "AZ": 52.17,
          "BS": 7.54,
          "BH": 21.73,
          "BD": 105.4,
          "BB": 3.96,
          "BY": 52.89,
          "BE": 131.33,
          "BZ": 1.43,
          "BJ": 6.49,
          "BT": 1.4,
          "BO": 3019.18,
          "BA": 16.2,
          "BW": 12.5,
          "BR": 2023.53,
          "BN": 11.96,
          "BG": 44.84,
          "BF": 8.67,
          "BI": 1.47,
          "KH": 11.36,
          "CM": 21.88,
          "CA": 53.66,
          "CV": 1.57,
          "CF": 2.11,
          "TD": 14087.59,
          "CL": 199.18,
          "CN": 5745.13,
          "CO": 283.11,
          "KM": 0.56,
          "CD": 312.6,
          "CG": 11.88,
          "CR": 35.02,
          "CI": 160.38,
          "CU": 478.95,
          "EH": 200.65,
          "PR": 20.78,
          "XK": 1060.67,
          "NC": 563.23,
          "SD": 3267.59,
          "XS": 100.6,
          "SO": 62.3,
          "KP": 135.78,
          "NZ": 500.5,
          "HR": 59.92,
          "CY": 22.75,
          "CZ": 495.23,
          "DK": 304.56,
          "DJ": 1.14,
          "DM": 0.38,
          "DO": 50.87,
          "EC": 61.49,
          "EG": 6.83,
          "SV": 21.8,
          "GQ": 14.55,
          "ER": 2.25,
          "EE": 19.22,
          "ET": 30.94,
          "FJ": 3.15,
          "FI": 231.98,
          "FR": 2555.44,
          "GA": 12.56,
          "GM": 1.04,
          "GE": 3211.23,
          "DE": 3305.9,
          "GH": 18.06,
          "GL": 150.0,
          "GR": 258.91,
          "GD": 0.65,
          "GT": 40.77,
          "GN": 14444.34,
          "GW": 0.83,
          "GY": 4000.2,
          "HT": 6.5,
          "HN": 157.34,
          "HK": 226.49,
          "HU": 132.28,
          "IS": 12.77,
          "IN": 30.02,
          "ID": 695.06,
          "IR": 337.9,
          "IQ": 84.14,
          "IE": 204.14,
          "IL": 201.25,
          "IT": 2036.69,
          "JM": 13.74,
          "JP": 5390.9,
          "JO": 27.13,
          "KZ": 129.76,
          "KE": 32.42,
          "KI": 0.15,
          "KR": 986.26,
          "KW": 117.32,
          "KG": 4.44,
          "LA": 6.34,
          "LV": 23.39,
          "LB": 39.15,
          "LS": 1.8,
          "LR": 0.98,
          "LY": 77.91,
          "LT": 35.73,
          "LU": 52.43,
          "MK": 9.58,
          "MG": 8.33,
          "MW": 5.04,
          "MY": 218.95,
          "MV": 1.43,
          "ML": 2599.08,
          "MT": 7.8,
          "MR": 765.49,
          "MU": 9.43,
          "MX": 3004.04,
          "MD": 5.36,
          "MN": 13255.81,
          "ME": 3.88,
          "MA": 3091.7,
          "MZ": 10.21,
          "MM": 35.65,
          "NA": 11.45,
          "NP": 152.11,
          "NL": 770.31,
          "NZ": 138,
          "NI": 6.38,
          "NE": 5.6,
          "NG": 206.66,
          "NO": 113.51,
          "OM": 53.78,
          "PK": 174.79,
          "PA": 27.2,
          "PG": 8.81,
          "PY": 137.17,
          "PE": 153.55,
          "PH": 189.06,
          "PL": 438.88,
          "PT": 223.7,
          "QA": 126.52,
          "RO": 8.39,
          "RU": 1476.91,
          "RW": 5.69,
          "WS": 0.55,
          "ST": 0.19,
          "SA": 434.44,
          "SN": 12.66,
          "RS": 38.92,
          "SC": 0.92,
          "SL": 1.9,
          "SG": 217.38,
          "SK": 86.26,
          "SS": 135.48,
          "SI": 46.44,
          "SB": 0.67,
          "ZA": 354.41,
          "ES": 13063.78,
          "LK": 48.24,
          "KN": 0.56,
          "LC": 1,
          "VC": 0.58,
          "SD": 65.93,
          "SR": 3.3,
          "SZ": 3.17,
          "SE": 444.59,
          "CH": 522.44,
          "SY": 59.63,
          "TW": 426.98,
          "TJ": 5.58,
          "TZ": 22.43,
          "TH": 312.61,
          "TL": 0.62,
          "TG": 3.07,
          "TO": 0.3,
          "TT": 21.2,
          "TN": 43.86,
          "TR": 729.05,
          "TM": 0,
          "UG": 17.12,
          "UA": 136.56,
          "AE": 239.65,
          "GB": 2258.57,
          "US": 14624.18,
          "UY": 14440.71,
          "UZ": 37.72,
          "VU": 0.72,
          "VE": 185.21,
          "VN": 101.99,
          "YE": 30.02,
          "ZM": 3315.69,
          "ZW": 5.57
        }
      }]
    }
  });
})
