/* 	<= BORNES DE COMMENTAIRE À RETIRER À L'AVENIR ============================>
	Dans l'idéal, le glossaire des termes culinaires devrait figurer dans
	une table séparée (par exemple, une base de données CSV) ; ci-dessous,
	voici le code pour une requête AJAX convoquant le CSV.
	<=========================================================================>
	
// Requête AJAX du fichier CSV

var glossaireCSV = new XMLHttpRequest();
var csv = "Je suis un texte";

// Quand le fichier est dispo
glossaireCSV.onreadystatechange = function() {

		console.log(glossaireCSV.readyState === 4);
		console.log(glossaireCSV.status === 200);

	// Resitution si le fichier est prêt pour le parsing et existe dans le dir
	if (glossaireCSV.readyState === 4 && glossaireCSV.status === 200) {
		console.log("je l'ai!");
		csv = glossaireCSV.responseText;
	}
};

console.log(csv);

// Ouverture du fichier
glossaireCSV.open("GET", "../dicos/glossaire.csv", true);
glossaireCSV.send;

// Maintenant qu'il est dispo, division du fichier csv en lignes
var lignes = csv.split(/\r\n|\n/);

// Création de la table de hachage (sous forme d'objet)
var glossaire = {};

// Itération dans chacune des lignes et création de couples lemme-définition
for(var i = 0; i < lignes.length; i++){
	var entree = lignes[i].split(';');

	// Stockage des lemmes en tant que clés et des définitions en tant que valeurs.
	var lemme = entree[0];
	var def = entree[1];
	
	// Création du couple clé-valeur
	def = glossaire[lemme];
}

	<= /BORNES DE COMMENTAIRE À RETIRER À L'AVENIR ===========================>

for (var clef in glossaire) {
	if (glossaire.hasOwnProperty(clef)) {
		
		// clés : les lemmes && valeurs : les définitions
		var lemme = clef;
		var def = glossaire[clef];
		// DEBUG :
		console.log(lemme + " : " + def);
		
		// On balise avec <def> chaque lemme matchant le glossaire
		var contentHTML = $("#texte-recette").html();
		contentHTML = contentHTML.replace(new RegExp(lemme, 'g'),
		'<span title="' + def + '">' + lemme + '</span>');
		$("#texte-recette").html(contentHTML);
	}
}
*/

// EN ATTENDANT... :

/* Dictionnaire fléchi */
var glossaireFlechi = {
	"abaissant": "abaisser",
	"abaisse": "abaisser",
	"abaissée": "abaisser",
	"abaisser": "abaisser",
	"abaisser": "abaisser",
	"abaissera": "abaisser",
	"abaisserez": "abaisser",
	"abaissez": "abaisser",
	"abaissez": "abaisser",
	"abricotez": "abricoter",
	"accordant": "accorder",
	"accorde": "accorder",
	"accordent": "accorder",
	"accorder": "accorder",
	"accordera": "accorder",
	"accorderait": "accorder",
	"accoucher": "accoucher",
	"adorais": "adorer",
	"adorant": "adorer",
	"adore": "adorer",
	"adoré": "adorer",
	"adoré": "adorer",
	"adorée": "adorer",
	"adorées": "adorer",
	"adorent": "adorer",
	"adorer": "adorer",
	"adorerez": "adorer",
	"adoreront": "adorer",
	"adorés": "adorer",
	"adorez": "adorer",
	"adorons": "adorer",
	"adressant": "adresser",
	"adresse": "adresser",
	"adressé": "adresser",
	"adressez": "adresser",
	"affilié": "affilier",
	"affleure": "affleurer",
	"affleurent": "affleurer",
	"affleurer": "affleurer",
	"alliant": "allier",
	"allie": "allier",
	"allie": "allier",
	"allié": "allier",
	"alliée": "allier",
	"allient": "allier",
	"allier": "allier",
	"arrosant": "arroser",
	"arrosant": "arroser",
	"arrose": "arroser",
	"arrosé": "arroser",
	"arrosé": "arroser",
	"arrosée": "arroser",
	"arrosées": "arroser",
	"arrosent": "arroser",
	"arroser": "arroser",
	"arroser": "arroser",
	"arrosera": "arroser",
	"arroserez": "arroser",
	"arroserons": "arroser",
	"arrosés": "arroser",
	"arrosez": "arroser",
	"arrosez": "arroser",
	"arrosons": "arroser",
	"aspic": "aspic",
	"aspic": "aspic",
	"aspic": "aspic",
	"aspics": "aspic",
	"assaisonnant": "assaisonner",
	"assaisonne": "assaisonner",
	"assaisonne": "assaisonner",
	"assaisonné": "assaisonner",
	"assaisonnée": "assaisonner",
	"assaisonnées": "assaisonner",
	"assaisonner": "assaisonner",
	"assaisonner": "assaisonner",
	"assaisonnerez": "assaisonner",
	"assaisonnés": "assaisonner",
	"assaisonnez": "assaisonner",
	"assaisonnez": "assaisonner",
	"atelier": "atelier",
	"ateliers": "atelier",
	"ateliers": "atelier",
	"bain-marie": "bain-marie",
	"bain-marie": "bain-marie",
	"barbe": "barbe",
	"barbe": "barbe",
	"barbeau": "barbeau",
	"barbecue": "barbecue",
	"barbecue": "barbecue",
	"barbecues": "barbecue",
	"barbera": "barber",
	"barbera": "barber",
	"barbes": "barbe",
	"barbet": "barbet",
	"barbets": "barbet",
	"bardé": "barder",
	"bardé": "barder",
	"bardée": "barder",
	"bardées": "barder",
	"barder": "barder",
	"barder": "barder",
	"bardes": "barder",
	"bardés": "barder",
	"bardez": "barder",
	"bardez": "barder",
	"bateliers": "batelier",
	"bélier": "bélier",
	"beurrant": "beurrer",
	"beurre": "beurrer",
	"beurre": "beurrer",
	"beurré": "beurrer",
	"beurré": "beurrer",
	"beurrée": "beurrer",
	"beurrées": "beurrer",
	"beurrent": "beurrer",
	"beurrer": "beurrer",
	"beurrer": "beurrer",
	"beurrer": "beurrer",
	"beurres": "beurrer",
	"beurrés": "beurrer",
	"beurrés": "beurrer",
	"beurrez": "beurrer",
	"beurrez": "beurrer",
	"blanc": "blanc",
	"blanc": "blanc",
	"blanc": "blanc",
	"blanchâtre": "blanchâtre",
	"blanchâtres": "blanchâtre",
	"blanche": "blanc",
	"blanche": "blanc",
	"blanches": "blanc",
	"blancheur": "blancheur",
	"blanchi": "blanchir",
	"blanchie": "blanchir",
	"blanchies": "blanchir",
	"blanchiment": "blanchiment",
	"blanchir": "blanchir",
	"blanchir": "blanchir",
	"blanchira": "blanchir",
	"blanchirez": "blanchir",
	"blanchis": "blanchir",
	"blanchissage": "blanchissage",
	"blanchissant": "blanchir",
	"blanchisse": "blanchir",
	"blanchissement": "blanchissement",
	"blanchissent": "blanchir",
	"blanchissez": "blanchir",
	"blanchissez": "blanchir",
	"blanchit": "blanchir",
	"blanc-manger": "blanc-manger",
	"blanc-manger": "blanc-manger",
	"blanc-manger": "blanc-manger",
	"blancs": "blanc",
	"blancs": "blanc",
	"blancs": "blanc",
	"blondi": "blondir",
	"blondie": "blondir",
	"blondie": "blondir",
	"blondies": "blondir",
	"blondir": "blondir",
	"blondir": "blondir",
	"blondis": "blondir",
	"blondisse": "blondir",
	"blondissent": "blondir",
	"blondit": "blondir",
	"bouclier": "bouclier",
	"boule": "bouler",
	"boulé": "bouler",
	"bouler": "bouler",
	"boules": "bouler",
	"braise": "braiser",
	"braisé": "braiser",
	"braisé": "braiser",
	"braisée": "braiser",
	"braisées": "braiser",
	"braiser": "braiser",
	"braiser": "braiser",
	"braises": "braiser",
	"braisés": "braiser",
	"braisez": "braiser",
	"bridé": "brider",
	"bridées": "brider",
	"brider": "brider",
	"brider": "brider",
	"bridez": "brider",
	"bridez": "brider",
	"brunoise": "brunoise",
	"cannelé": "canneler",
	"cannelée": "canneler",
	"cannelées": "canneler",
	"canneler": "canneler",
	"cannelés": "canneler",
	"cannelés": "canneler",
	"cannelez": "canneler",
	"cannelle": "canneler",
	"cannelle": "canneler",
	"caramélisant": "caraméliser",
	"caramélise": "caraméliser",
	"caramélisé": "caraméliser",
	"caramélisée": "caraméliser",
	"caramélisées": "caraméliser",
	"caramélisent": "caraméliser",
	"caraméliser": "caraméliser",
	"caraméliser": "caraméliser",
	"caramélisera": "caraméliser",
	"caraméliseront": "caraméliser",
	"caramélisés": "caraméliser",
	"caramélisez": "caraméliser",
	"caramélisez": "caraméliser",
	"carcasse": "carcasse",
	"carcasses": "carcasse",
	"cavaliers": "cavalier",
	"cavaliers": "cavalier",
	"cellier": "cellier",
	"châtrées": "châtrer",
	"châtrer": "châtrer",
	"chemise": "chemiser",
	"chemisé": "chemiser",
	"chemisée": "chemiser",
	"chemiser": "chemiser",
	"chemiser": "chemiser",
	"chemisés": "chemiser",
	"chemisez": "chemiser",
	"chemisez": "chemiser",
	"chevalier": "chevalier",
	"chevaliers": "chevalier",
	"chiffonnade": "chiffonnade",
	"chiffonnade": "chiffonnade",
	"chiffonnades": "chiffonnade",
	"chinois": "chinois",
	"chinois": "chinois",
	"chinoise": "chinois",
	"chinoiser": "chinoiser",
	"chinoises": "chinois",
	"ciselant": "ciseler",
	"ciselé": "ciseler",
	"ciselée": "ciseler",
	"ciselées": "ciseler",
	"ciseler": "ciseler",
	"ciseler": "ciseler",
	"ciselés": "ciseler",
	"ciselez": "ciseler",
	"ciselez": "ciseler",
	"clarifie": "clarifier",
	"clarifié": "clarifier",
	"clarifier": "clarifier",
	"clarifier": "clarifier",
	"clarifiez": "clarifier",
	"clarifiez": "clarifier",
	"clouté": "clouter",
	"clouter": "clouter",
	"cloutés": "clouter",
	"cloutez": "clouter",
	"collaient": "coller",
	"collant": "coller",
	"colle": "coller",
	"collé": "coller",
	"collée": "coller",
	"collées": "coller",
	"collent": "coller",
	"coller": "coller",
	"coller": "coller",
	"collera": "coller",
	"collerette": "collerette",
	"collerettes": "collerette",
	"colleront": "coller",
	"collés": "coller",
	"collez": "coller",
	"collez": "coller",
	"collier": "collier",
	"collier": "collier",
	"colliers": "collier",
	"compare": "comparer",
	"comparée": "comparer",
	"comparent": "comparer",
	"comparer": "comparer",
	"comparés": "comparer",
	"concassant": "concasser",
	"concassé": "concasser",
	"concassé": "concasser",
	"concassée": "concasser",
	"concassées": "concasser",
	"concasser": "concasser",
	"concasser": "concasser",
	"concasser": "concasser",
	"concassés": "concasser",
	"concassez": "concasser",
	"concassez": "concasser",
	"concassez": "concasser",
	"concilier": "concilier",
	"concordent": "concorder",
	"confira": "confire",
	"confire": "confire",
	"confire": "confire",
	"confis": "confire",
	"confise": "confire",
	"confisent": "confire",
	"confisse": "confire",
	"confit": "confire",
	"confit": "confire",
	"confit": "confire",
	"confite": "confire",
	"confites": "confire",
	"confites": "confire",
	"confits": "confire",
	"confits": "confire",
	"contourné": "contourner",
	"contourner": "contourner",
	"contrefilet": "contrefilet",
	"contre-filet": "contre-filet",
	"cordon": "cordon",
	"cordon": "cordon",
	"cordon-bleu": "cordon-bleu",
	"cordons": "cordon",
	"cordons": "cordon",
	"cornas": "corner",
	"corner": "corner",
	"corsait": "corser",
	"corse": "corser",
	"corsé": "corser",
	"corsé": "corser",
	"corsée": "corser",
	"corser": "corser",
	"corsera": "corser",
	"corsés": "corser",
	"couchant": "coucher",
	"couche": "coucher",
	"couché": "coucher",
	"couchée": "coucher",
	"couchées": "coucher",
	"coucher": "coucher",
	"coucher": "coucher",
	"couches": "coucher",
	"couchés": "coucher",
	"couchez": "coucher",
	"couchez": "coucher",
	"crémant": "crémer",
	"crémant": "crémer",
	"crème": "crémer",
	"crème": "crémer",
	"crémée": "crémer",
	"crémer": "crémer",
	"crémer": "crémer",
	"crémerie": "crémerie",
	"crémés": "crémer",
	"crémez": "crémer",
	"crevant": "crever",
	"crève": "crever",
	"crèvent": "crever",
	"crever": "crever",
	"crever": "crever",
	"crevés": "crever",
	"crevez": "crever",
	"cuisson": "cuisson",
	"cuisson": "cuisson",
	"cuisson": "cuisson",
	"cuissons": "cuisson",
	"cuissons": "cuisson",
	"culière": "culier",
	"débardé": "débarder",
	"débarder": "débarder",
	"débarrassant": "débarrasser",
	"débarrasse": "débarrasser",
	"débarrassé": "débarrasser",
	"débarrassée": "débarrasser",
	"débarrassées": "débarrasser",
	"débarrassent": "débarrasser",
	"débarrasser": "débarrasser",
	"débarrasser": "débarrasser",
	"débarrassés": "débarrasser",
	"débarrassez": "débarrasser",
	"débarrassez": "débarrasser",
	"débridez": "débrider",
	"décalant": "décaler",
	"décalé": "décaler",
	"décalées": "décaler",
	"décaler": "décaler",
	"décanter": "décanter",
	"décanter": "décanter",
	"décantera": "décanter",
	"décantez": "décanter",
	"décantez": "décanter",
	"décarcasser": "décarcasser",
	"décarcassez": "décarcasser",
	"décarcassez": "décarcasser",
	"déchiquetant": "déchiqueter",
	"déchiqueté": "déchiqueter",
	"déchiquetée": "déchiqueter",
	"déchiquetées": "déchiqueter",
	"déchiqueter": "déchiqueter",
	"déchiqueter": "déchiqueter",
	"déchiquetez": "déchiqueter",
	"déchiquetez": "déchiqueter",
	"décollant": "décoller",
	"décolle": "décoller",
	"décollé": "décoller",
	"décollée": "décoller",
	"décollent": "décoller",
	"décoller": "décoller",
	"décoller": "décoller",
	"décollera": "décoller",
	"décollés": "décoller",
	"décollez": "décoller",
	"décollez": "décoller",
	"décollons": "décoller",
	"dégermé": "dégermer",
	"dégermée": "dégermer",
	"dégermées": "dégermer",
	"dégermer": "dégermer",
	"dégermer": "dégermer",
	"dégermez": "dégermer",
	"dégermez": "dégermer",
	"déglaçant": "déglacer",
	"déglace": "déglacer",
	"déglacé": "déglacer",
	"déglacée": "déglacer",
	"déglacées": "déglacer",
	"déglacer": "déglacer",
	"déglacer": "déglacer",
	"déglacerez": "déglacer",
	"déglacés": "déglacer",
	"déglacez": "déglacer",
	"déglacez": "déglacer",
	"déglaçons": "déglacer",
	"dégorge": "dégorger",
	"dégorgé": "dégorger",
	"dégorgeaient": "dégorger",
	"dégorgée": "dégorger",
	"dégorgées": "dégorger",
	"dégorgent": "dégorger",
	"dégorger": "dégorger",
	"dégorger": "dégorger",
	"dégorgés": "dégorger",
	"dégorgez": "dégorger",
	"dégrainés": "dégrainer",
	"dégraissé": "dégraisser",
	"dégraissée": "dégraisser",
	"dégraissées": "dégraisser",
	"dégraisser": "dégraisser",
	"dégraisser": "dégraisser",
	"dégraissés": "dégraisser",
	"dégraissez": "dégraisser",
	"dégraissez": "dégraisser",
	"délié": "délier",
	"délier": "délier",
	"délier": "délier",
	"déliez": "délier",
	"déliez": "délier",
	"démonte": "démonter",
	"démontent": "démonter",
	"démonter": "démonter",
	"dénervant": "dénerver",
	"dénervé": "dénerver",
	"dénervée": "dénerver",
	"dénervées": "dénerver",
	"dénerver": "dénerver",
	"dénerver": "dénerver",
	"dénervés": "dénerver",
	"dénervez": "dénerver",
	"dénervez": "dénerver",
	"dénervons": "dénerver",
	"dépassaient": "dépasser",
	"dépassait": "dépasser",
	"dépassant": "dépasser",
	"dépasse": "dépasser",
	"dépassé": "dépasser",
	"dépassées": "dépasser",
	"dépassent": "dépasser",
	"dépasser": "dépasser",
	"dépassera": "dépasser",
	"dépasseront": "dépasser",
	"dépassez": "dépasser",
	"dépliée": "déplier",
	"dépliées": "déplier",
	"déplier": "déplier",
	"déplier": "déplier",
	"dépliez": "déplier",
	"dépliez": "déplier",
	"dépouille": "dépouiller",
	"dépouillé": "dépouiller",
	"dépouiller": "dépouiller",
	"dépouiller": "dépouiller",
	"dépouillés": "dépouiller",
	"dépouillez": "dépouiller",
	"dépouillez": "dépouiller",
	"déshabillé": "déshabiller",
	"déshabiller": "déshabiller",
	"déshabiller": "déshabiller",
	"désosse": "désosser",
	"désossé": "désosser",
	"désossée": "désosser",
	"désossées": "désosser",
	"désosser": "désosser",
	"désosser": "désosser",
	"désossés": "désosser",
	"désossez": "désosser",
	"désossez": "désosser",
	"dessèche": "dessécher",
	"desséché": "dessécher",
	"desséchée": "dessécher",
	"desséchées": "dessécher",
	"dessèchent": "dessécher",
	"dessécher": "dessécher",
	"dessécher": "dessécher",
	"desséchés": "dessécher",
	"desséchez": "dessécher",
	"desséchez": "dessécher",
	"détaillant": "détailler",
	"détaille": "détailler",
	"détaillé": "détailler",
	"détaillé": "détailler",
	"détaillée": "détailler",
	"détaillées": "détailler",
	"détailler": "détailler",
	"détailler": "détailler",
	"détaillerez": "détailler",
	"détailles": "détailler",
	"détaillés": "détailler",
	"détaillez": "détailler",
	"détaillez": "détailler",
	"détendant": "détendre",
	"détendez": "détendre",
	"détendez": "détendre",
	"détendra": "détendre",
	"détendre": "détendre",
	"détendre": "détendre",
	"détendu": "détendre",
	"détendue": "détendre",
	"détendues": "détendre",
	"détendus": "détendre",
	"détourez": "détourer",
	"détourné": "détourner",
	"détournée": "détourner",
	"détourner": "détourner",
	"détrempe": "détrempe",
	"détrempé": "détremper",
	"détrempée": "détremper",
	"détrempées": "détremper",
	"détrempent": "détremper",
	"détremper": "détremper",
	"détrempés": "détremper",
	"dévoilant": "dévoiler",
	"dévoile": "dévoiler",
	"dévoilé": "dévoiler",
	"dévoiler": "dévoiler",
	"doraient": "dorer",
	"dorant": "dorer",
	"dore": "dorer",
	"doré": "dorer",
	"dorée": "dorer",
	"dorées": "dorer",
	"dorées": "dorer",
	"dorent": "dorer",
	"dorer": "dorer",
	"dorer": "dorer",
	"dorerez": "dorer",
	"doreront": "dorer",
	"dores": "dorer",
	"dorés": "dorer",
	"dorez": "dorer",
	"dorez": "dorer",
	"dresse": "dresser",
	"dressé": "dresser",
	"dressée": "dresser",
	"dressées": "dresser",
	"dresser": "dresser",
	"dresser": "dresser",
	"dresserez": "dresser",
	"dressés": "dresser",
	"dressez": "dresser",
	"dressez": "dresser",
	"duxelles": "duxelles",
	"duxelles": "duxelles",
	"ébarber": "ébarber",
	"ébarber": "ébarber",
	"ébarbés": "ébarber",
	"ébarbez": "ébarber",
	"ébarbez": "ébarber",
	"écaillé": "écailler",
	"écaillée": "écailler",
	"écaillées": "écailler",
	"écailler": "écailler",
	"écailler": "écailler",
	"écaillera": "écailler",
	"écaillés": "écailler",
	"écaillez": "écailler",
	"écalé": "écaler",
	"écalées": "écaler",
	"écalent": "écaler",
	"écaler": "écaler",
	"écaler": "écaler",
	"écalés": "écaler",
	"écalez": "écaler",
	"écolier": "écolier",
	"écoliers": "écolier",
	"écossant": "écosser",
	"écossées": "écosser",
	"écosser": "écosser",
	"écosser": "écosser",
	"écossés": "écosser",
	"écossez": "écosser",
	"écossez": "écosser",
	"écrémé": "écrémer",
	"écrémée": "écrémer",
	"écrémer": "écrémer",
	"écumant": "écumer",
	"écume": "écumer",
	"écumé": "écumer",
	"écument": "écumer",
	"écumer": "écumer",
	"écumer": "écumer",
	"écumez": "écumer",
	"écumez": "écumer",
	"effeuillant": "effeuiller",
	"effeuille": "effeuiller",
	"effeuillé": "effeuiller",
	"effeuillée": "effeuiller",
	"effeuillées": "effeuiller",
	"effeuillent": "effeuiller",
	"effeuiller": "effeuiller",
	"effeuiller": "effeuiller",
	"effeuillés": "effeuiller",
	"effeuillez": "effeuiller",
	"effeuillez": "effeuiller",
	"effeuillons": "effeuiller",
	"effleurant": "effleurer",
	"effleure": "effleurer",
	"effleurent": "effleurer",
	"effleurer": "effleurer",
	"effleurez": "effleurer",
	"égouttant": "égoutter",
	"égoutte": "égoutter",
	"égoutté": "égoutter",
	"égouttée": "égoutter",
	"égouttées": "égoutter",
	"égouttent": "égoutter",
	"égoutter": "égoutter",
	"égoutter": "égoutter",
	"égoutterez": "égoutter",
	"égouttés": "égoutter",
	"égouttez": "égoutter",
	"égouttez": "égoutter",
	"égouttons": "égoutter",
	"égrainant": "égrainer",
	"égrainé": "égrainer",
	"égrainée": "égrainer",
	"égrainées": "égrainer",
	"égrainer": "égrainer",
	"égrainer": "égrainer",
	"égrainez": "égrainer",
	"égrenant": "égrener",
	"égrène": "égrener",
	"égrené": "égrener",
	"égrenée": "égrener",
	"égrenées": "égrener",
	"égrener": "égrener",
	"égrener": "égrener",
	"égrenés": "égrener",
	"égrenez": "égrener",
	"égrenez": "égrener",
	"éminçant": "émincer",
	"émince": "émincer",
	"émincé": "émincer",
	"émincé": "émincer",
	"émincée": "émincer",
	"émincées": "émincer",
	"émincer": "émincer",
	"émincer": "émincer",
	"émincerez": "émincer",
	"éminces": "émincer",
	"émincés": "émincer",
	"émincés": "émincer",
	"émincez": "émincer",
	"émincez": "émincer",
	"émondé": "émonder",
	"émondée": "émonder",
	"émondées": "émonder",
	"émonder": "émonder",
	"émonder": "émonder",
	"émondés": "émonder",
	"émondez": "émonder",
	"émondez": "émonder",
	"emparez": "emparer",
	"empilant": "empiler",
	"empilées": "empiler",
	"empilent": "empiler",
	"empiler": "empiler",
	"empiler": "empiler",
	"empilez": "empiler",
	"empilez": "empiler",
	"encoller": "encoller",
	"enfonçant": "enfoncer",
	"enfonce": "enfoncer",
	"enfoncé": "enfoncer",
	"enfoncée": "enfoncer",
	"enfoncent": "enfoncer",
	"enfoncer": "enfoncer",
	"enfoncer": "enfoncer",
	"enfoncerez": "enfoncer",
	"enfonceront": "enfoncer",
	"enfoncés": "enfoncer",
	"enfoncez": "enfoncer",
	"enfoncez": "enfoncer",
	"enrobant": "enrober",
	"enrobe": "enrober",
	"enrobé": "enrober",
	"enrobée": "enrober",
	"enrobées": "enrober",
	"enrobent": "enrober",
	"enrober": "enrober",
	"enrober": "enrober",
	"enrobera": "enrober",
	"enroberont": "enrober",
	"enrobés": "enrober",
	"enrobez": "enrober",
	"enrobez": "enrober",
	"enserrant": "enserrer",
	"enserriez": "enserrer",
	"entourait": "entourer",
	"entourant": "entourer",
	"entoure": "entourer",
	"entouré": "entourer",
	"entourée": "entourer",
	"entourées": "entourer",
	"entourent": "entourer",
	"entourer": "entourer",
	"entourer": "entourer",
	"entourerez": "entourer",
	"entourés": "entourer",
	"entourez": "entourer",
	"entourez": "entourer",
	"entrelardé": "entrelarder",
	"entrelarder": "entrelarder",
	"entrelardés": "entrelarder",
	"épile": "épiler",
	"épiler": "épiler",
	"épluchait": "éplucher",
	"épluchant": "éplucher",
	"épluche": "éplucher",
	"épluché": "éplucher",
	"épluchée": "éplucher",
	"épluchées": "éplucher",
	"épluchent": "éplucher",
	"éplucher": "éplucher",
	"éplucher": "éplucher",
	"épluchera": "éplucher",
	"éplucherez": "éplucher",
	"éplucheront": "éplucher",
	"épluchés": "éplucher",
	"épluchez": "éplucher",
	"épluchez": "éplucher",
	"épluchons": "éplucher",
	"escalier": "escalier",
	"escalope": "escaloper",
	"escalope": "escaloper",
	"escalopé": "escaloper",
	"escalopées": "escaloper",
	"escaloper": "escaloper",
	"escaloper": "escaloper",
	"escalopes": "escaloper",
	"escalopez": "escaloper",
	"escalopez": "escaloper",
	"étuve": "étuver",
	"étuvé": "étuver",
	"étuvée": "étuver",
	"étuvées": "étuver",
	"étuver": "étuver",
	"étuver": "étuver",
	"étuvés": "étuver",
	"étuvez": "étuver",
	"évidant": "évider",
	"évidé": "évider",
	"évidée": "évider",
	"évidées": "évider",
	"évider": "évider",
	"évider": "évider",
	"évidera": "évider",
	"évidés": "évider",
	"évidez": "évider",
	"évidez": "évider",
	"exprimant": "exprimer",
	"exprime": "exprimer",
	"exprimé": "exprimer",
	"expriment": "exprimer",
	"exprimer": "exprimer",
	"exprimer": "exprimer",
	"exprimez": "exprimer",
	"exprimez": "exprimer",
	"farce": "farce",
	"farce": "farce",
	"farce": "farce",
	"farcer": "farcer",
	"farces": "farce",
	"farcez": "farcer",
	"faux-filet": "faux-filet",
	"faux-filet": "faux-filet",
	"faux-filets": "faux-filet",
	"filet": "filet",
	"filet": "filet",
	"filet": "filet",
	"fileter": "fileter",
	"fileter": "fileter",
	"filets": "filet",
	"filets": "filet",
	"filets": "filet",
	"flambant": "flamber",
	"flambe": "flamber",
	"flambé": "flamber",
	"flambé": "flamber",
	"flambée": "flamber",
	"flambées": "flamber",
	"flamber": "flamber",
	"flamber": "flamber",
	"flamberez": "flamber",
	"flambés": "flamber",
	"flambez": "flamber",
	"flambez": "flamber",
	"fleure": "fleurer",
	"foisonnée": "foisonner",
	"fonça": "foncer",
	"fonce": "foncer",
	"foncé": "foncer",
	"foncée": "foncer",
	"foncent": "foncer",
	"foncer": "foncer",
	"foncer": "foncer",
	"foncés": "foncer",
	"foncez": "foncer",
	"foncez": "foncer",
	"fontaine": "fontaine",
	"fontainebleau": "fontainebleau",
	"fontainebleau": "fontainebleau",
	"foulant": "fouler",
	"foulez": "fouler",
	"fraisant": "fraiser",
	"fraise": "fraiser",
	"fraiser": "fraiser",
	"fraiser": "fraiser",
	"fraises": "fraiser",
	"fraises": "fraiser",
	"fraisez": "fraiser",
	"fraisez": "fraiser",
	"frémi": "frémir",
	"frémie": "frémir",
	"frémir": "frémir",
	"frémira": "frémir",
	"frémissant": "frémir",
	"frémisse": "frémir",
	"frémissent": "frémir",
	"frémit": "frémir",
	"frire": "frire",
	"frire": "frire",
	"fris": "frire",
	"frit": "frire",
	"frite": "frire",
	"frites": "frire",
	"frites": "frire",
	"frits": "frire",
	"fumet": "fumet",
	"fumet": "fumet",
	"fumets": "fumet",
	"gastrique": "gastrique",
	"glaçant": "glacer",
	"glace": "glacer",
	"glace": "glacer",
	"glacé": "glacer",
	"glacé": "glacer",
	"glacée": "glacer",
	"glacées": "glacer",
	"glacent": "glacer",
	"glacer": "glacer",
	"glacer": "glacer",
	"glacés": "glacer",
	"glacez": "glacer",
	"glacez": "glacer",
	"glaçons": "glacer",
	"glissant": "glisser",
	"glisse": "glisser",
	"glissé": "glisser",
	"glissée": "glisser",
	"glissent": "glisser",
	"glisser": "glisser",
	"glisser": "glisser",
	"glissera": "glisser",
	"glisserez": "glisser",
	"glisseront": "glisser",
	"glissez": "glisser",
	"glissez": "glisser",
	"graine": "grainer",
	"graines": "grainer",
	"grainez": "grainer",
	"gratinant": "gratiner",
	"gratine": "gratiner",
	"gratiné": "gratiner",
	"gratiné": "gratiner",
	"gratinée": "gratiner",
	"gratinée": "gratiner",
	"gratinées": "gratiner",
	"gratinées": "gratiner",
	"gratinent": "gratiner",
	"gratiner": "gratiner",
	"gratiner": "gratiner",
	"gratinera": "gratiner",
	"gratines": "gratiner",
	"gratinés": "gratiner",
	"gratinez": "gratiner",
	"gratinez": "gratiner",
	"grillant": "griller",
	"grille": "griller",
	"grillé": "griller",
	"grillée": "griller",
	"grillées": "griller",
	"grillent": "griller",
	"griller": "griller",
	"griller": "griller",
	"grillerez": "griller",
	"grilleront": "griller",
	"grilles": "griller",
	"grillés": "griller",
	"grillés": "griller",
	"grillez": "griller",
	"grillez": "griller",
	"habillé": "habiller",
	"habillée": "habiller",
	"habillées": "habiller",
	"habillent": "habiller",
	"habiller": "habiller",
	"habiller": "habiller",
	"habillez": "habiller",
	"hachant": "hacher",
	"hache": "hacher",
	"haché": "hacher",
	"haché": "hacher",
	"hachée": "hacher",
	"hachée": "hacher",
	"hachées": "hacher",
	"hachent": "hacher",
	"hacher": "hacher",
	"hacher": "hacher",
	"hachera": "hacher",
	"hacherez": "hacher",
	"haches": "hacher",
	"hachés": "hacher",
	"hachez": "hacher",
	"hachez": "hacher",
	"hâtelet": "hâtelet",
	"hâtelets": "hâtelet",
	"historier": "historier",
	"hôtelière": "hôtelier",
	"illustre": "illustrer",
	"incisant": "inciser",
	"incise": "inciser",
	"incisé": "inciser",
	"incisée": "inciser",
	"incisées": "inciser",
	"inciser": "inciser",
	"inciser": "inciser",
	"inciserez": "inciser",
	"incisez": "inciser",
	"incisez": "inciser",
	"incisons": "inciser",
	"incorporant": "incorporer",
	"incorpore": "incorporer",
	"incorpore": "incorporer",
	"incorporé": "incorporer",
	"incorporée": "incorporer",
	"incorporées": "incorporer",
	"incorporent": "incorporer",
	"incorporer": "incorporer",
	"incorporer": "incorporer",
	"incorporera": "incorporer",
	"incorporerait": "incorporer",
	"incorporerez": "incorporer",
	"incorporeront": "incorporer",
	"incorporés": "incorporer",
	"incorporez": "incorporer",
	"incorporez": "incorporer",
	"incorporons": "incorporer",
	"infusé": "infuser",
	"infusée": "infuser",
	"infusent": "infuser",
	"infuser": "infuser",
	"infuser": "infuser",
	"infusera": "infuser",
	"infuseront": "infuser",
	"infusés": "infuser",
	"infusez": "infuser",
	"infusez": "infuser",
	"interrompez": "interrompre",
	"interrompre": "interrompre",
	"interrompt": "interrompre",
	"interrompus": "interrompre",
	"irrégulier": "irrégulier",
	"irrégulière": "irrégulier",
	"irrégulières": "irrégulier",
	"irréguliers": "irrégulier",
	"journalier": "journalier",
	"journaliers": "journalier",
	"julienne": "julienne",
	"juliennes": "julienne",
	"lardé": "larder",
	"lardée": "larder",
	"lardées": "larder",
	"larder": "larder",
	"larder": "larder",
	"lardés": "larder",
	"lardez": "larder",
	"lardons": "larder",
	"lardons": "larder",
	"liant": "lier",
	"lie": "lier",
	"lié": "lier",
	"liée": "lier",
	"liées": "lier",
	"lient": "lier",
	"lier": "lier",
	"lier": "lier",
	"liera": "lier",
	"lierre": "lierre",
	"liés": "lier",
	"liez": "lier",
	"liez": "lier",
	"limone": "limoner",
	"lissant": "lisser",
	"lisse": "lisser",
	"lissé": "lisser",
	"lissée": "lisser",
	"lisser": "lisser",
	"lisser": "lisser",
	"lisserez": "lisser",
	"lissez": "lisser",
	"lissez": "lisser",
	"lustrer": "lustrer",
	"lustrer": "lustrer",
	"luttent": "lutter",
	"lutter": "lutter",
	"luttez": "lutter",
	"macérant": "macérer",
	"macère": "macérer",
	"macéré": "macérer",
	"macérée": "macérer",
	"macérées": "macérer",
	"macèrent": "macérer",
	"macérer": "macérer",
	"macérer": "macérer",
	"macérés": "macérer",
	"macérez": "macérer",
	"marbrant": "marbrer",
	"marbré": "marbrer",
	"marbré": "marbrer",
	"marbrée": "marbrer",
	"marbrées": "marbrer",
	"marbrer": "marbrer",
	"marbrés": "marbrer",
	"marbrez": "marbrer",
	"marinant": "mariner",
	"marine": "mariner",
	"mariné": "mariner",
	"mariné": "mariner",
	"marinée": "mariner",
	"marinées": "mariner",
	"marinent": "mariner",
	"mariner": "mariner",
	"mariner": "mariner",
	"marinera": "mariner",
	"marinés": "mariner",
	"marinez": "mariner",
	"marinez": "mariner",
	"marquant": "marquer",
	"marque": "marquer",
	"marqué": "marquer",
	"marquées": "marquer",
	"marquer": "marquer",
	"marquer": "marquer",
	"marqués": "marquer",
	"marquez": "marquer",
	"masque": "masquer",
	"masqué": "masquer",
	"masquée": "masquer",
	"masquent": "masquer",
	"masquer": "masquer",
	"masquer": "masquer",
	"masquera": "masquer",
	"masquerait": "masquer",
	"masqués": "masquer",
	"masquez": "masquer",
	"masquez": "masquer",
	"massant": "masser",
	"massé": "masser",
	"masser": "masser",
	"masser": "masser",
	"massez": "masser",
	"massez": "masser",
	"mijotait": "mijoter",
	"mijotant": "mijoter",
	"mijote": "mijoter",
	"mijoté": "mijoter",
	"mijoté": "mijoter",
	"mijotée": "mijoter",
	"mijotée": "mijoter",
	"mijotées": "mijoter",
	"mijotent": "mijoter",
	"mijoter": "mijoter",
	"mijoter": "mijoter",
	"mijotera": "mijoter",
	"mijoteront": "mijoter",
	"mijotés": "mijoter",
	"mijotez": "mijoter",
	"milliers": "millier",
	"mirepoix": "mirepoix",
	"mirepoix": "mirepoix",
	"mondé": "monder",
	"mondée": "monder",
	"mondées": "monder",
	"monder": "monder",
	"monder": "monder",
	"mondés": "monder",
	"mondez": "monder",
	"montaient": "monter",
	"montant": "monter",
	"montant": "monter",
	"mont-blanc": "mont-blanc",
	"monte": "monter",
	"monte": "monter",
	"monté": "monter",
	"montée": "monter",
	"montées": "monter",
	"montent": "monter",
	"monter": "monter",
	"monter": "monter",
	"montera": "monter",
	"monterez": "monter",
	"monteront": "monter",
	"montés": "monter",
	"montez": "monter",
	"montez": "monter",
	"montpellier": "montpellier",
	"mouillant": "mouiller",
	"mouille": "mouiller",
	"mouillé": "mouiller",
	"mouillé": "mouiller",
	"mouillée": "mouiller",
	"mouillées": "mouiller",
	"mouiller": "mouiller",
	"mouiller": "mouiller",
	"mouillerez": "mouiller",
	"mouillés": "mouiller",
	"mouillez": "mouiller",
	"mouillez": "mouiller",
	"multipliant": "multiplier",
	"multiplie": "multiplier",
	"multiplié": "multiplier",
	"multiplier": "multiplier",
	"multiplier": "multiplier",
	"multipliez": "multiplier",
	"multipliez": "multiplier",
	"nacre": "nacrer",
	"nacré": "nacrer",
	"nacrer": "nacrer",
	"nacrés": "nacrer",
	"nacrez": "nacrer",
	"nappant": "napper",
	"nappe": "napper",
	"nappe": "napper",
	"nappé": "napper",
	"nappé": "napper",
	"nappée": "napper",
	"nappées": "napper",
	"nappent": "napper",
	"napper": "napper",
	"napper": "napper",
	"nappera": "napper",
	"napperez": "napper",
	"napperon": "napperon",
	"napperont": "napper",
	"nappés": "napper",
	"nappez": "napper",
	"nappez": "napper",
	"nappons": "napper",
	"odorant": "odorer",
	"oubliant": "oublier",
	"oublie": "oublier",
	"oublié": "oublier",
	"oubliée": "oublier",
	"oubliées": "oublier",
	"oublient": "oublier",
	"oublier": "oublier",
	"oublier": "oublier",
	"oubliera": "oublier",
	"oublieraient": "oublier",
	"oublierez": "oublier",
	"oublieront": "oublier",
	"oubliés": "oublier",
	"oubliez": "oublier",
	"oubliez": "oublier",
	"oublions": "oublier",
	"palier": "palier",
	"paliers": "palier",
	"pallier": "pallier",
	"panais": "paner",
	"panais": "paner",
	"pane": "paner",
	"pané": "paner",
	"panée": "paner",
	"panées": "paner",
	"paner": "paner",
	"paner": "paner",
	"panés": "paner",
	"panez": "paner",
	"particulier": "particulier",
	"particulier": "particulier",
	"particulière": "particulier",
	"particulières": "particulier",
	"particuliers": "particulier",
	"passait": "passer",
	"passant": "passer",
	"passe": "passer",
	"passe": "passer",
	"passé": "passer",
	"passé": "passer",
	"passée": "passer",
	"passée": "passer",
	"passées": "passer",
	"passées": "passer",
	"passent": "passer",
	"passer": "passer",
	"passer": "passer",
	"passera": "passer",
	"passerez": "passer",
	"passeriez": "passer",
	"passeront": "passer",
	"passés": "passer",
	"passés": "passer",
	"passez": "passer",
	"passez": "passer",
	"passions": "passer",
	"passons": "passer",
	"passons": "passer",
	"pâton": "pâton",
	"pâtons": "pâton",
	"persillade": "persillade",
	"persillade": "persillade",
	"pilant": "piler",
	"pile": "piler",
	"pilé": "piler",
	"pilée": "piler",
	"pilées": "piler",
	"piler": "piler",
	"piler": "piler",
	"pilèrent": "piler",
	"pilerez": "piler",
	"pilés": "piler",
	"pilez": "piler",
	"pilez": "piler",
	"pilons": "piler",
	"pinçant": "pincer",
	"pince": "pincer",
	"pincé": "pincer",
	"pincée": "pincer",
	"pincées": "pincer",
	"pincent": "pincer",
	"pincer": "pincer",
	"pincer": "pincer",
	"pincés": "pincer",
	"pincez": "pincer",
	"pincez": "pincer",
	"piquant": "piquer",
	"pique": "piquer",
	"piqué": "piquer",
	"piquée": "piquer",
	"piquées": "piquer",
	"piquent": "piquer",
	"piquer": "piquer",
	"piquer": "piquer",
	"piquera": "piquer",
	"piquerez": "piquer",
	"piqueront": "piquer",
	"piqués": "piquer",
	"piquez": "piquer",
	"piquez": "piquer",
	"piquons": "piquer",
	"pliant": "plier",
	"plie": "plier",
	"plié": "plier",
	"pliée": "plier",
	"pliées": "plier",
	"plier": "plier",
	"plier": "plier",
	"pliera": "plier",
	"plierez": "plier",
	"pliés": "plier",
	"pliez": "plier",
	"pliez": "plier",
	"plissant": "plisser",
	"plissé": "plisser",
	"plissées": "plisser",
	"plisser": "plisser",
	"plissés": "plisser",
	"plissez": "plisser",
	"pluches": "pluches",
	"poche": "pocher",
	"poché": "pocher",
	"pochée": "pocher",
	"pochées": "pocher",
	"pocher": "pocher",
	"pocher": "pocher",
	"pochés": "pocher",
	"pochez": "pocher",
	"pochez": "pocher",
	"poêlant": "poêler",
	"poêle": "poêler",
	"poêlé": "poêler",
	"poêlé": "poêler",
	"poêlée": "poêler",
	"poêlée": "poêler",
	"poêlées": "poêler",
	"poêlées": "poêler",
	"poêler": "poêler",
	"poêler": "poêler",
	"poêlés": "poêler",
	"poêlez": "poêler",
	"poêlez": "poêler",
	"poussant": "pousser",
	"pousse": "pousser",
	"poussé": "pousser",
	"poussée": "pousser",
	"poussent": "pousser",
	"pousser": "pousser",
	"pousser": "pousser",
	"poussez": "pousser",
	"poussez": "pousser",
	"préparaient": "préparer",
	"préparais": "préparer",
	"préparait": "préparer",
	"préparant": "préparer",
	"prépare": "préparer",
	"prépare": "préparer",
	"prépare": "préparer",
	"préparé": "préparer",
	"préparé": "préparer",
	"préparée": "préparer",
	"préparée": "préparer",
	"préparées": "préparer",
	"préparées": "préparer",
	"préparent": "préparer",
	"préparer": "préparer",
	"préparer": "préparer",
	"préparera": "préparer",
	"préparerait": "préparer",
	"préparerez": "préparer",
	"prépareront": "préparer",
	"préparés": "préparer",
	"préparés": "préparer",
	"préparez": "préparer",
	"préparez": "préparer",
	"préparez": "préparer",
	"prépariez": "préparer",
	"préparons": "préparer",
	"préparons": "préparer",
	"prusse": "prusse",
	"publie": "publier",
	"publié": "publier",
	"publiées": "publier",
	"quadrillant": "quadriller",
	"quadrillé": "quadriller",
	"quadrillé": "quadriller",
	"quadrillée": "quadriller",
	"quadriller": "quadriller",
	"quadriller": "quadriller",
	"quadrillez": "quadriller",
	"quadrillez": "quadriller",
	"rabaisser": "rabaisser",
	"rabaisser": "rabaisser",
	"rabat": "rabattre",
	"rabattant": "rabattre",
	"rabattez": "rabattre",
	"rabattez": "rabattre",
	"rabattre": "rabattre",
	"rabattre": "rabattre",
	"rabattue": "rabattre",
	"rabattues": "rabattre",
	"rabattus": "rabattre",
	"raffermie": "raffermir",
	"raffermir": "raffermir",
	"raffermir": "raffermir",
	"raffermira": "raffermir",
	"raffermiront": "raffermir",
	"raffermisse": "raffermir",
	"raffermissent": "raffermir",
	"raffermit": "raffermir",
	"rafraîchi": "rafraîchir",
	"rafraîchie": "rafraîchir",
	"rafraîchies": "rafraîchir",
	"rafraîchir": "rafraîchir",
	"rafraîchir": "rafraîchir",
	"rafraîchira": "rafraîchir",
	"rafraîchis": "rafraîchir",
	"rafraîchissant": "rafraîchir",
	"rafraîchissant": "rafraîchir",
	"rafraîchisse": "rafraîchir",
	"rafraîchissent": "rafraîchir",
	"rafraîchissez": "rafraîchir",
	"rafraîchissez": "rafraîchir",
	"rafraîchit": "rafraîchir",
	"raidir": "raidir",
	"raidis": "raidir",
	"raidisse": "raidir",
	"raidissent": "raidir",
	"raidit": "raidir",
	"rallie": "rallier",
	"ramasse": "ramasser",
	"ramassé": "ramasser",
	"ramassent": "ramasser",
	"ramasser": "ramasser",
	"ramasser": "ramasser",
	"ramassés": "ramasser",
	"ramassez": "ramasser",
	"ramassez": "ramasser",
	"recoller": "recoller",
	"réconciliant": "réconcilier",
	"réconcilie": "réconcilier",
	"réconciliée": "réconcilier",
	"réconcilier": "réconcilier",
	"réconciliez": "réconcilier",
	"recuisson": "recuisson",
	"redorer": "redorer",
	"redorez": "redorer",
	"redresser": "redresser",
	"redressez": "redresser",
	"réduira": "réduire",
	"réduiraient": "réduire",
	"réduirait": "réduire",
	"réduire": "réduire",
	"réduire": "réduire",
	"réduirez": "réduire",
	"réduiront": "réduire",
	"réduis": "réduire",
	"réduisant": "réduire",
	"réduise": "réduire",
	"réduisent": "réduire",
	"réduisez": "réduire",
	"réduisez": "réduire",
	"réduisiez": "réduire",
	"réduit": "réduire",
	"réduite": "réduire",
	"réduites": "réduire",
	"réduits": "réduire",
	"reglisses": "reglisser",
	"régulier": "régulier",
	"régulière": "régulier",
	"régulières": "régulier",
	"réguliers": "régulier",
	"réincorporé": "réincorporer",
	"réincorporer": "réincorporer",
	"réincorporer": "réincorporer",
	"réincorporez": "réincorporer",
	"relevait": "relever",
	"relevant": "relever",
	"relève": "relever",
	"relève": "relever",
	"relevé": "relever",
	"relevée": "relever",
	"relevées": "relever",
	"relèvent": "relever",
	"relever": "relever",
	"relever": "relever",
	"relèvera": "relever",
	"relèveront": "relever",
	"relevés": "relever",
	"relevez": "relever",
	"relevez": "relever",
	"relie": "relier",
	"reliées": "relier",
	"relier": "relier",
	"relier": "relier",
	"remarque": "remarquer",
	"remarqué": "remarquer",
	"remarquera": "remarquer",
	"remarquerez": "remarquer",
	"remarquez": "remarquer",
	"remontant": "remonter",
	"remonte": "remonter",
	"remonté": "remonter",
	"remontée": "remonter",
	"remontées": "remonter",
	"remontent": "remonter",
	"remonter": "remonter",
	"remonter": "remonter",
	"remonteraient": "remonter",
	"remonterait": "remonter",
	"remonteront": "remonter",
	"remontes": "remonter",
	"remontés": "remonter",
	"remontez": "remonter",
	"remontez": "remonter",
	"remouiller": "remouiller",
	"remouiller": "remouiller",
	"remouillez": "remouiller",
	"remplie": "remplier",
	"répare": "réparer",
	"repassant": "repasser",
	"repasse": "repasser",
	"repassé": "repasser",
	"repassée": "repasser",
	"repasser": "repasser",
	"repasser": "repasser",
	"repassera": "repasser",
	"repassez": "repasser",
	"repassez": "repasser",
	"repiquer": "repiquer",
	"repliant": "replier",
	"replie": "replier",
	"replié": "replier",
	"repliée": "replier",
	"repliées": "replier",
	"replier": "replier",
	"replier": "replier",
	"replierez": "replier",
	"repliés": "replier",
	"repliez": "replier",
	"repliez": "replier",
	"repoussant": "repousser",
	"repousse": "repousser",
	"repousser": "repousser",
	"ressemblance": "ressemblance",
	"resserrer": "resserrer",
	"resserrez": "resserrer",
	"retournant": "retourner",
	"retourne": "retourner",
	"retourné": "retourner",
	"retournée": "retourner",
	"retournée": "retourner",
	"retournées": "retourner",
	"retournent": "retourner",
	"retourner": "retourner",
	"retourner": "retourner",
	"retournera": "retourner",
	"retournerez": "retourner",
	"retournés": "retourner",
	"retournez": "retourner",
	"retournez": "retourner",
	"retournons": "retourner",
	"retournons": "retourner",
	"retravaille": "retravailler",
	"retravailler": "retravailler",
	"retravailler": "retravailler",
	"retravaillez": "retravailler",
	"retravaillez": "retravailler",
	"retrempé": "retremper",
	"retremper": "retremper",
	"retrempez": "retremper",
	"retrousser": "retrousser",
	"retroussez": "retrousser",
	"retroussez": "retrousser",
	"revenant": "revenir",
	"revenant": "revenir",
	"revenez": "revenir",
	"revenez": "revenir",
	"revenir": "revenir",
	"revenir": "revenir",
	"revenons": "revenir",
	"revenons": "revenir",
	"revenu": "revenir",
	"revenue": "revenir",
	"revenues": "revenir",
	"revenus": "revenir",
	"reviendrait": "revenir",
	"reviendrez": "revenir",
	"revienne": "revenir",
	"reviennent": "revenir",
	"reviens": "revenir",
	"revient": "revenir",
	"rhubarbe": "rhubarbe",
	"rhubarbe": "rhubarbe",
	"rhubarbes": "rhubarbe",
	"rissole": "rissoler",
	"rissolé": "rissoler",
	"rissolé": "rissoler",
	"rissolée": "rissoler",
	"rissolées": "rissoler",
	"rissolent": "rissoler",
	"rissoler": "rissoler",
	"rissoler": "rissoler",
	"rissolés": "rissoler",
	"rissolez": "rissoler",
	"rissolez": "rissoler",
	"rompe": "rompre",
	"rompent": "rompre",
	"rompez": "rompre",
	"rompre": "rompre",
	"rompre": "rompre",
	"rompt": "rompre",
	"rôti": "rôtir",
	"rôti": "rôtir",
	"rôtie": "rôtir",
	"rôtie": "rôtir",
	"rôties": "rôtir",
	"rôtir": "rôtir",
	"rôtir": "rôtir",
	"rôtis": "rôtir",
	"rôtis": "rôtir",
	"rôtissant": "rôtir",
	"rôtisse": "rôtir",
	"rôtissent": "rôtir",
	"rôtissez": "rôtir",
	"rouelle": "rouelle",
	"rouelle": "rouelle",
	"rouelle": "rouelle",
	"rouelles": "rouelle",
	"rouelles": "rouelle",
	"rousse": "roux",
	"rousses": "roux",
	"roux": "roux",
	"ruban": "ruban",
	"rubans": "ruban",
	"russe": "russe",
	"russe": "russe",
	"russes": "russe",
	"saisi": "saisir",
	"saisie": "saisir",
	"saisies": "saisir",
	"saisir": "saisir",
	"saisir": "saisir",
	"saisis": "saisir",
	"saisissant": "saisir",
	"saisisse": "saisir",
	"saisissez": "saisir",
	"saisissez": "saisir",
	"saisit": "saisir",
	"sanglier": "sanglier",
	"sanglier": "sanglier",
	"saute": "sauter",
	"sauté": "sauter",
	"sauté": "sauter",
	"sautées": "sauter",
	"sautent": "sauter",
	"sauter": "sauter",
	"sauter": "sauter",
	"sautera": "sauter",
	"sauterelles": "sauterelle",
	"sauternes": "sauternes",
	"sauternes": "sauternes",
	"sauternes": "sauternes",
	"sautés": "sauter",
	"sautés": "sauter",
	"sautez": "sauter",
	"sautez": "sauter",
	"séparant": "séparer",
	"sépare": "séparer",
	"sépare": "séparer",
	"séparé": "séparer",
	"séparée": "séparer",
	"séparées": "séparer",
	"séparent": "séparer",
	"séparer": "séparer",
	"séparer": "séparer",
	"séparera": "séparer",
	"séparerez": "séparer",
	"séparés": "séparer",
	"séparez": "séparer",
	"séparez": "séparer",
	"séparons": "séparer",
	"serra": "serrer",
	"serrant": "serrer",
	"serre": "serrer",
	"serré": "serrer",
	"serrée": "serrer",
	"serrées": "serrer",
	"serrer": "serrer",
	"serrer": "serrer",
	"serrera": "serrer",
	"serrés": "serrer",
	"serrez": "serrer",
	"serrez": "serrer",
	"singer": "singer",
	"singer": "singer",
	"singez": "singer",
	"singulière": "singulier",
	"sommelier": "sommelier",
	"sommelière": "sommelier",
	"sue": "suer",
	"sué": "suer",
	"suent": "suer",
	"suer": "suer",
	"suer": "suer",
	"sués": "suer",
	"supplieront": "supplier",
	"suprême": "suprême",
	"suprême": "suprême",
	"suprêmement": "suprêmement",
	"suprêmes": "suprême",
	"suprêmes": "suprême",
	"suprêmes": "suprême",
	"surmontant": "surmonter",
	"surmonté": "surmonter",
	"surmontée": "surmonter",
	"surmontées": "surmonter",
	"surmonter": "surmonter",
	"surmonter": "surmonter",
	"surmontés": "surmonter",
	"surmontez": "surmonter",
	"surmontez": "surmonter",
	"tablier": "tablier",
	"tablier": "tablier",
	"tabliers": "tablier",
	"tamisant": "tamiser",
	"tamise": "tamiser",
	"tamisé": "tamiser",
	"tamisée": "tamiser",
	"tamisées": "tamiser",
	"tamiser": "tamiser",
	"tamiser": "tamiser",
	"tamisés": "tamiser",
	"tamisez": "tamiser",
	"tamisez": "tamiser",
	"tamponnant": "tamponner",
	"tamponnées": "tamponner",
	"tamponner": "tamponner",
	"tamponnez": "tamponner",
	"templiers": "templier",
	"torréfié": "torréfier",
	"torréfiée": "torréfier",
	"torréfiées": "torréfier",
	"torréfier": "torréfier",
	"torréfier": "torréfier",
	"torréfiés": "torréfier",
	"tourer": "tourer",
	"tournant": "tourner",
	"tourne": "tourner",
	"tourné": "tourner",
	"tournée": "tourner",
	"tournées": "tourner",
	"tournent": "tourner",
	"tourner": "tourner",
	"tourner": "tourner",
	"tournerait": "tourner",
	"tournés": "tourner",
	"tournez": "tourner",
	"tournez": "tourner",
	"tournons": "tourner",
	"travaillais": "travailler",
	"travaillait": "travailler",
	"travaillant": "travailler",
	"travaille": "travailler",
	"travaillé": "travailler",
	"travaillée": "travailler",
	"travaillées": "travailler",
	"travailler": "travailler",
	"travailler": "travailler",
	"travaillerait": "travailler",
	"travaillés": "travailler",
	"travaillez": "travailler",
	"travaillez": "travailler",
	"trempaient": "tremper",
	"trempait": "tremper",
	"trempant": "tremper",
	"trempe": "tremper",
	"trempé": "tremper",
	"trempée": "tremper",
	"trempées": "tremper",
	"trempées": "tremper",
	"trempent": "tremper",
	"tremper": "tremper",
	"tremper": "tremper",
	"trempera": "tremper",
	"tremperez": "tremper",
	"tremperont": "tremper",
	"trempes": "tremper",
	"trempés": "tremper",
	"trempés": "tremper",
	"trempez": "tremper",
	"trempez": "tremper",
	"trempons": "tremper",
	"tronçon": "tronçon",
	"tronçonne": "tronçonner",
	"tronçonné": "tronçonner",
	"tronçonnée": "tronçonner",
	"tronçonnées": "tronçonner",
	"tronçonner": "tronçonner",
	"tronçonner": "tronçonner",
	"tronçonnés": "tronçonner",
	"tronçonnez": "tronçonner",
	"tronçonnez": "tronçonner",
	"tronçons": "tronçon",
	"trousser": "trousser",
	"turbinant": "turbiner",
	"turbiner": "turbiner",
	"turbinez": "turbiner",
	"vanner": "vanner",
	"venaison": "venaison",
	"voila": "voiler",
	"voila": "voiler",
	"voila": "voiler",
	"zeste": "zeste",
	"zeste": "zeste",
	"zestée": "zester",
	"zestées": "zester",
	"zester": "zester",
	"zester": "zester",
	"zestes": "zeste",
	"zestes": "zeste",
	"zesteur": "zesteur",
	"zestez": "zester",
	"zestez": "zester",
	};

/* Glossaire des termes (lemmes) et de leur définition */

var glossaire = {
	"abaisser": "étendre une pâte à une épaisseur voulue à l’aide d’un rouleau à pâtisserie.",
	"abricoter": "déposer au pinceau une fine couche de nappage blond, sur une tarte ou un entremet, pour en améliorer la présentation finale",
	"arroser": "imprégner une viande au cours de sa cuisson avec sa propre matière grasse. évite ainsi le dessèchement et donne une belle coloration",
	"assaisonner": "ajouter en quantité suffisante, du sel, du poivre ou des épices à un met ou une préparation culinaire",
	"aspic": "entrée froide, moulée et gélifiée",
	"bain-marie": "1. récipient destiné à maintenir au chaud les sauces ou potages. il est placé dans un autre récipient contenant de l’eau bouillante. 2. technique de cuisson suivant le même procédé, destinée à certaines préparations délicates qui requièrent une cuisson douce et homogène.",
	"barbe": "petites nageoires transversales (pourtour de la sole par exemple)",
	"barder": "mince couche de lard gras, maintenue sur une pièce de boucherie, de volaille, ou de gibier. evite le dessèchement de la pièce durant sa cuisson",
	"beurre en pommade": "beurre frais, ramolli et travaillé à la spatule jusqu’à obtenir la consistance d’une pommade. la pommade doit être homogène et sans morceaux",
	"beurre manié": "mélange de beurre en pommade et de farine permettant de lier (donner de la consistance) une sauce. le beurre manié permet, ajouté en petite quantité à la sauce bouillante, d'obtenir la consistance recherchée",
	"beurrer": "enduire un moule, un plat, un papier sulfurisé de beurre avec un pinceau pour empêcher les aliments de coller",
	"blanc": "mélange de farine (facultatif), d’eau, de citron, de sel et d’huile utilisé pour la cuisson de certains légumes dans le but de conserver la couleur blanche",
	"blanc de poireaux": "base du légume, c'est la partie blanche du poireau. la plus tendre et la plus appréciée",
	"blanchir": "1. plonger des légumes dans de l’eau bouillante salée quelques minutes puis rafraîchir et égoutter pour éliminer l’âcreté. 2. pour la viande, immerger dans de l’eau froide et porter à ébullition pour éliminer l’excédent de sel, les impuretés ou raffermir les chairs. 3. pour la pâtisserie, fouetter des jaunes et sucre semoule jusqu’à l’obtention d’un mélange blanc.",
	"blondir": "colorer très légèrement un aliment jusqu’à l’obtention d’une couleur blonde",
	"bouler": "rouler des boules de pâtes dans le creux de la main en effectuant un mouvement circulaire de façon à obtenir des boules régulières et homogènes (pâtes brisée, à brioche)",
	"bouquet garni": "queues de persil, du thym et du laurier ficelés solidement. selon les utilisations, on peut y ajouter des verts de poireaux ou une branche de céleri",
	"braiser": "mode de cuisson : cuire lentement, à couvert au four, une pièce de viande ou de poisson sur une garniture aromatique et dans un liquide de cuisson",
	"brider": "fixer les membres d’une volaille à l’aide d’une aiguille à brider et de ficelle, le but est de donner à la pièce une bonne présentation et d'en régulariser la cuisson",
	"brunoise": "légumes taillés en dés réguliers de 2mm de section, utilisés dans les potage ou les sauces",
	"canneler": "pratiquer des petites cannelures, à l’aide d’un canneleur, à la surface de certains fruits pour améliorer la présentation",
	"caraméliser": "1. enduire un moule avec du sucre cuit ou caramel. 2. synonyme de pincer (caraméliser les sucs de cuisson)",
	"carcasse": "ensemble osseux d’un animal, squelette",
	"cardinaliser": "faire revenir vivement des crustacés ou des carapaces de crustacés jusqu’à ce qu’ils obtiennent une couleur rouge",
	"châtrer": "éliminer le boyau central des écrevisses avant de les marquer en cuisson",
	"chaufroiter": "napper des pièces froides de buffet avec de la sauce chaud-froid (velouté crémé et collé à la gelée)",
	"chemiser": "enduire ou appliquer contre les parois intérieures d’un moule une couche de gelée, glace, pain de mie, beurre, laitue, ou de biscuit… avant de remplir le centre du moule avec une autre préparation",
	"chiffonnade": "laitue ou oseille taillée (ciselée) en fines lanières et étuvée au beurre, utilisée comme garniture de certains potages ou comme éléments de décoration",
	"chinois": "passoire fine, généralement conique, utilisée en particulier pour passer (c'est-à-dire filtrer) les sauces. on distingue le chinois traditionnel du chinois dit étamine, constituant un tamis. son nom vient probablement de sa forme qui évoque le traditionnel chapeau chinois",
	"chinoiser": "passer au chinois (passoire conique)",
	"chiqueter": "améliorer la présentation des bords d’une abaisse de pâte (brisée, à foncer…) en pratiquant de petites entailles à l’aide d’une pince à chiqueter",
	"ciseler": "détailler des échalotes ou des oignons en petits dés réguliers",
	"citronner": "frotter la surface de certains fruits ou légumes avec du citron pour éviter leur brunissement au contact de l’air ou pendant la cuisson",
	"clarifier": "1. clarifier c’est, filtrer, rendre limpide un liquide, une sauce, se débarrasser des impuretés. 2. séparer les blancs des jaunes d’oeufs. 3. fondre du beurre au bain marie pour séparer la matière grasse du petit lait",
	"clouter": "1. introduire des clous de girofle dans un oignon. 2. introduire à la surface d’une viande, d’une volaille ou d’un poisson, des petits bâtonnets de jambon, de truffe, etc.",
	"coller": " modifier ou raffermir la consistance de certaines préparations par l’addition de feuilles de gélatine",
	"compoter": "cuire doucement et régulièrement des oignons ou des poivrons jusqu’à l’aspect d’une compote",
	"concasser": "hacher grossièrement",
	"confire": "1. cuire très longtemps et lentement de la viande, d’oie ou de canard dans sa graisse. 2. cuire des fruits des zestes, progressivement dans un sirop de plus en plus concentré. 3. conserver des fruits ou des légumes dans de l’alcool, du vinaigre ou de l’huile",
	"corder": "état d’une pâte ou d’une purée de pommes de terre dont la consistance devient élastique",
	"cordon": "sauce que l’on dresse régulièrement tout autour d’une pièce (cordon de sauce)",
	"corner": "1. nettoyer soigneusement l’intérieur d’un récipient à l’aide d’une corne ou d’une marise. 2. débarrasser l’appareil d’un récipient à l’aide d’une corne ou d’une marise",
	"corser": "augmenter la saveur d’un met, soit par addition d’éléments sapides, soit par réduction",
	"coucher": " façonner des choux, des éclairs ou des meringues sur une plaque à pâtisserie à l’aide d’une poche munie d’une douille.",
	"crémer": " 1. ajouter de la crème à une préparation. 2. mélanger vigoureusement du sucre et du beurre en pommade au fouet ou à la spatule, jusqu’à l’obtention d’un mélange crémeux.",
	"crever": " plonger du riz (lavé) dans de l’eau froide et porter l’ensemble à ébullition durant quelques minutes jusqu’à éclatement des grains.",
	"croustades": " bouchées plates de formes diverses, réalisées généralement avec du feuilletage.",
	"cuire à blanc": " cuire à couvert, dans un grand volume d’eau bouillante salée, citronnée, farinée et huilée pour éviter les risques d'oxydation du produit.",
	"cuire à l'anglaise": " action de cuire des légumes dans une grande quantité d’eau bouillante salée, au terme de la cuisson les légumes sont immédiatement refroidis dans de l’eau glacée.",
	"cuisson": " action de cuire, s’emploie également pour désigner le liquide dans lequel a cuit l’aliment.",
	"cuisson à blanc": " action de pré-cuire une pâte avant de la garnir.",
	"cuits à blanc": " cuisson de certains légumes dans un mélange de farine (facultatif), d’eau, de citron, de sel et d’huile permettant de conserver la couleur blanche du produit.",
	"darnes": " tranches de poisson rond de 2 à 3 cm d’épaisseur (pour une personne).",
	"débarrasser": " transvaser ou placer un aliment solide ou liquide dans un récipient de stockage (calotte, bahut, plaque à débarrasser…).",
	"décanter": "séparer les différents éléments d’une préparation. 1. décanter du beurre clarifié : éliminer la caséine en surface et le petit lait. 2. décanter un ragoût : séparer la viande de sa garniture aromatique.",
	"dégermer": " fendre des gousses d’ail en deux afin d’enlever le germe (indigeste).",
	"déglacer": " dissoudre par l’apport d’un liquide les sucs caramélisés au fond d’un récipient.",
	"dégorger": " 1. saler un légumes à cru afin de lui rendre son eau de végétation (concombre, choux). 2. laisser un aliment sous l’eau courante (arêtes de poissons, abats, etc.) pour enlever le sang et les impuretés.",
	"dégraisser": " 1. supprimer l’excédent de graisse à la surface d’une viande avant cuisson. 2. enlever la graisse d’un récipient, d’un bouillon, d’un fond, d’une sauce.",
	"dénerver": " eliminer la fine pellicule nerveuse ou les aponévroses d’une pièce de viande.",
	"dépouiller": " 1. eliminer les impuretés qui surnagent à la surface d’un liquide (fonds, potages, etc). 2. enlever la peau d’un lapin, lièvre, anguille, sole, etc...",
	"désarêter": " supprimer les arêtes d’un filet de poisson à l’aide d’une pince à désarêter.",
	"désosser": "retirer les os d’une viande, d’une volaille, à cru ou après cuisson.",
	"désosseur": " lame rigide, pointue d'une taille de 11 à 17 cm permettant de désosser les volailles, viandes crues...",
	"dessécher": " travailler une préparation épaisse (pâte, purée) sur le feu afin de la raffermir.",
	"détailler": "couper uniformément en morceaux à l'aide d'un couteau correctement aiguisé.",
	"détendre": "donner à une préparation (sauce, potage) une consistance plus fluide en lui ajoutant un liquide.",
	"détrempe": " pâte composée de farine, d’eau et de sel, servant à réaliser la pâte feuilletée.",
	"dorer": "etendre de la dorure (jaune et eau battus) au pinceau sur une pâte avant cuisson, le but est de favoriser une belle coloration durant la cuisson.",
	"dresser": "disposer harmonieusement et avec soin des mets sur une assiette ou un plat.",
	"duxelles": " préparation à base de champignons de paris hachés cuits, utilisée comme farce.",
	"ébarber": " 1. supprimer les nageoires d’un poisson cru ou cuit. 2. enlever les filaments d’un oeuf poché ou les « barbes » d’une huître.",
	"écailler": " 1. supprimer les écailles d’un poisson à l’aide d’un écailleur. 2. frotter les pattes des volailles après les avoir flambées.",
	"écaler": "enlever la coquille d’un oeuf cuit (mollet ou dur) ou d’une noix.",
	"écosser": " enlever l’enveloppe de certains légumes (petits pois, fèves, haricots en grains).",
	"écumer": " enlever l’écume (albumine) qui se forme à la surface de certaines préparations liquide en ébullition, à l’aide d’une écumoire ou d’un pochon.",
	"effeuiller": " séparer les feuilles des tiges (herbes aromatiques).",
	"éffiler": " eliminer les fils des haricots verts.",
	"égoutter": " mettre un aliment dans une passoire ou un chinois pour en éliminer l’eau.",
	"égrener": " séparer, aérer, les grains de semoule ou de riz après cuisson à l’aide d’une fourchette.",
	"émincer": " tailler des légumes ou fruits en fines tranches.",
	"emulsion ou emulsionner": " une émulsion est une dispersion de deux liquides, non miscibles entre eux (vinaigre et huile par exemple). la stabilité d'une émulsion est conditionnée par l'emploi d'un émulsifiant comme le jaune d’œuf. il existe donc les émulsions instables et les émulsions stables.",
	"enrober": " recouvrir uniformément un aliment d’une préparation onctueuse (pâte à frire, chocolat, etc.)",
	"éplucher": " oter les parties non comestibles d’un aliment.",
	"escaloper": " couper en biais des tranches de viande ou des champignons.",
	"étuver": " cuire doucement et à couvert un aliment dans son eau de végétation avec un peu de beurre.",
	"évider": " creuser l’intérieur de certains légumes ou fruits afin de les farcir.",
	"exprimer": "extraire l’eau ou le jus d’un aliment en le pressant fortement.",
	"farce": " préparation à base d’éléments crus ou cuits hachés finement et assaisonnés.",
	"filet": " 1. partie comestible la plus noble de l’animal (boeuf, sole, volaille, etc.) 2. petite quantité d’huile d’olive, de citron, ajoutée à une préparation.",
	"filet de sole": "le filet de sole est un couteau de 15 à 22 cm à lame très fine, flexible et acérée qui permet de lever les filets de poissons.",
	"fileter": "lever des filets de poissons.",
	"filetés": " filets de poissons levés.",
	"flamber": "1. passer une volaille ou gibier au contact d’une flamme pour le débarrasser des duvets. 2. arroser une préparation d’alcool et l’enflammer.",
	"fleurer": " fariner très légèrement un plan de travail pour éviter aux pâtes de coller.",
	"fleurons": "petites pièces en rognures de pâte feuilletée de formes diverses (croissant, poisson).",
	"foisonner": " fouetter énergiquement une préparation pour alléger sa consistance en incorporant de l’air ou en l’émulsionnant.",
	"foncer": " 1. garnir le fond d’un récipient d’une garniture aromatique avant de braiser un aliment. 2. garnir le fond et les parois d’un moule ou d’un cercle avec une abaisse de pâte.",
	"fond blanc": " bouillon blanc de veau ou de volaille aromatisé.",
	"fond brun": " bouillon brun obtenu à partir d’os ou de carcasses de volaille et d’une garniture aromatique. c’est la base des sauces dérivées et des ragoûts à brun.",
	"fontaine": "forme de puits donné à la farine pour la réalisation de pâtes.",
	"fouler": " passer au chinois une préparation en appuyant fortement avec un pochon pour en exprimer le maximum.",
	"fraiser": " écraser une pâte par petites quantités avec la paume de la main ou une corne pour la rendre homogène.",
	"frémir": " maintenir un liquide à une température légèrement inférieure à celle de l’ébullition (pochage des oeufs).",
	"frire": "cuire un aliment par immersion dans un corps gras monté à haute température.",
	"fumet": "1. bouillon obtenu par la cuisson des arêtes de poissons ou os de gibiers et d’une garniture aromatique. 2. arômes dégagés par une préparation culinaire.",
	"gastrique": "caramélisation blonde de sucre et de vinaigre. la gastrique est utilisée comme base à l'élaboration des sauces aigres-douces.",
	"glacer": "1. cuire des légumes dans un peu d’eau, du sel, du sucre et du beurre, les légumes sont glacés à blanc, ou glacés à brun. 2. napper certaines pâtisseries de fondant blanc, de chocolat, de caramel (choux, éclairs, etc.) 3. colorer la surface d’une pièce poêlée; avec son fond de cuisson en l’exposant à la chaleur d’un four jusqu’à obtenir une pellicule brillante. 4. gratiner légèrement sous la salamandre un sabayon ou une sauce poisson riche en crème et beurre.",
	"glacer à blanc": "apporter un aspect brillant à des petits oignons ou des légumes tournés",
	"glacer à brun": "apporter une couleur dorée à des petits oignons ou des légumes tournés",
	"glacés à blanc": "petits oignons ou légumes tournés auxquels on a apporté un aspect brillant.",
	"grainer": "blancs d’oeufs montés en neige à la texture hétérogène laissant apparaître des petits grains.",
	"gratiner": "colorer à la salamandre la surface d’un plat à l’aide de gruyère râpé, de parmesan ou de chapelure.",
	"griller": "exposer un aliment de petite taille à la chaleur directe d’un gril ou d’un barbecue.",
	"habiller": "1. flamber, parer, vider, brider une volaille ou un gibier à plumes avant la mise en cuisson. 2. ebarber, écailler, vider, laver, éponger un poisson avant la mise en cuisson.",
	"hacher": "couper en petits morceaux des aliments divers.",
	"hâtelet": "tige de métal servant à maintenir un décor sur une grosse pièce.",
	"historier": "inciser en forme de dent de loup, à l’aide d’un couteau d’office, un fruit ou un légume (citron, melon, tomate, etc.)",
	"inciser": "faire des incisions à la surface d’un filet de poisson ou d’un filet de canard pour en faciliter la cuisson et parfaire la présentation.",
	"incorporer": "mélanger un aliment à un autre.",
	"infuser": "mettre une substance aromatique dans un liquide (chaud) pour le parfumer (vanille, cannelle, etc.)",
	"julienne": "filaments de 4 à 5 cm de long sur 2 mm de section. taille utilisée pour les légumes, fruits, zestes, etc.",
	"larder": "introduire à l’aide d’une lardoire, de gros bâtonnets de lard gras dans une pièce de viande (cuisson braisée).",
	"lier": "épaissir un liquide à l’aide d’un élément de liaison (roux, fécule diluée, jaunes d’oeufs, etc...)",
	"limoner": "enlever après trempage, les peaux et les parties sanguinolentes de certains abats.",
	"lisser": "1. fouetter énergiquement une préparation afin de lui donner une consistance lisse et homogène. 2. masquer et égaliser soigneusement un entremet d’une crème de base (mousseline, crème au beurre, etc.)",
	"lustrer": "recouvrir un met, de gelée, de beurre fondu, de nappage, à l’aide d’un pinceau, pour améliorer sa présentation en lui donnant un aspect brillant.",
	"lutter": "coller le couvercle d’un récipient hermétiquement à l’aide d’une pâte composée de farine et d’eau appelée « repère ».",
	"macérer": "mettre des fruits dans un alcool afin qu’ils s’imprègnent du parfum. eventuellement on peut y ajouter du sucre, des zestes d’agrumes, de la vanille, etc.",
	"manchonner": "dégager la chair qui recouvre la tête de l’os (côtes, pilons, suprêmes de volaille, etc.) pour favoriser la présentation.",
	"marbrer": "réaliser un décor au cornet sur du fondant à la surface d’un mille-feuille (marbrer un mille-feuille) ou tout autre décor sur fond d’assiette.",
	"mariner": "tremper de la viande, du gibier, ou du poisson, dans une préparation liquide très aromatique afin d’attendrir et de parfumer les chairs. (idéal pour le barbecue).",
	"marquer": "démarrer la cuisson d’un aliment.",
	"masquer": "recouvrir uniformément un entremet d’une crème de base (crème mousseline, crème au beurre, glaçage au chocolat, etc.)",
	"masser": "se dit d’un sirop de sucre qui cristallise. il blanchit, se trouble, puis laisse apparaître des cristaux de sucre.",
	"matignon": "garniture aromatique taillée en paysanne (carrés ou triangles de 0.5 cm de côté et 2 mm d’épaisseur) suée au beurre et déglacée au vin blanc.",
	"mignonette": "poivre en grains concassé.",
	"mijoter": "cuire lentement à feu doux.",
	"mirepoix": "taille de légume en cubes réguliers de section variable. utilisée en garniture aromatique, elle se compose en général de carottes, d’oignons, de céleri, de poitrine de porc et d’un bouquet garni.",
	"monder": "enlever la peau de certains légumes ou fruits, on les plonge dans de l’eau bouillante quelques secondes, et on les rafraîchit dans de l’eau glacée (tomates, pêches, amandes, etc.)",
	"monter": "1. fouetter une préparation afin d’incorporer de l’air et augmenter ainsi son volume (blancs d’oeufs, appareil à génoise). 2. incorporer de l’huile ou du beurre dans une sauce en fouettant « émulsionner » (sauce mayonnaise, beurre blanc).",
	"mortifier": "laisser reposer une viande avant son emploi afin de l’attendrir.",
	"mouiller": "ajouter un liquide (eau, fond, vin, etc.) à une préparation afin de permettre sa cuisson.",
	"nacrer": "faire revenir sans coloration du riz dans de la matière grasse (teinte proche de la nacre). c’est un phase de réalisation du riz cuit pilaf.",
	"napper": "recouvrir uniformément une préparation de sauce ou de crème.",
	"paner": "recouvrir uniformément un aliment de chapelure, de panure, après l’avoir passé dans l’anglaise (oeufs battus).",
	"panoufle": "partie ventrale de la selle anglaise.",
	"parer": "supprimer les parties non comestibles ou non utilisées d'une volaille, d'un poisson, d'un légume, etc, avant son utilisation.",
	"parures": "parties ou déchets nuisant à la présentation d’un aliment.",
	"passer": "faire passer un aliment ou une préparation au travers d’une passoire, d’un chinois, ou d’un tamis, soit pour l’égoutter ou soit pour éliminer les parties non consommables. exemple : passer une farce au tamis pour la rendre plus fine.",
	"pâton": "morceau de pâte non détaillée. un pâton de feuilletage.",
	"persillade": "mélange de chapelure, d’ail et de persil hachés, d’huile d’olive.",
	"persillée": "se dit d’une viande qui présente de fines infiltrations de gras dans le muscle. signe d’une viande de bonne qualité.",
	"piler": "réduire un aliment en purée à l’aide d’un mortier et d’un pilon.",
	"pincer": "1. caraméliser les sucs de cuisson d’une viande au fond du récipient de cuisson. etape pour la réalisation de sauces par déglaçage. 2. denteler le pourtour d’une pièce de pâtisserie à l’aide d’une pince à tarte ou avec les doigts. le but est de favoriser la présentation.",
	"piquer": "faire des trous dans une abaisse de pâte pour l’empêcher de gonfler pendant la cuisson.",
	"pluches": "feuilles de cerfeuil, persil, de cresson employés pour améliorer la présentation de certains potages.",
	"pocher": "cuire un aliment par immersion dans un liquide (eau, fonds, sirop, etc.)",
	"poêler": "cuire au four une pièce entière de viande ou de volaille sur une garniture aromatique dans un récipient creux muni d’un couvercle. ce mode de cuisson permet de parfumer et d’attendrir les chairs.",
	"pommes à l’anglaise": "pommes de terre pelées, cuites dans de l'eau salée, démarrage dans de l'eau froide, pendant une vingtaine de minutes environ.",
	"pousser": "faire augmenter le volume d’une pâte levée (à brioche, à pain, à baba, etc.) sous l’action des levures et de la chaleur (20 à 30 °c).",
	"préparer": "préparer une volaille ou un gibier, c'est-à-dire : plumer, vider, flamber, nettoyer.",
	"puncher": "imbiber au pinceau un biscuit, une génoise, d’un sirop aromatisé au rhum pour apporter du moelleux.",
	"quadriller": "marquer un aliment sur un gril afin d’obtenir un quadrillage en losange.",
	"rabattre": "replier sur elle même une pâte levée (à brioche) avec la paume de la main afin de répartir uniformément les levures à l’intérieur de la pâte et chasser le gaz carbonique.",
	"raffermir": " placer dans une enceinte réfrigérée un appareil, une pâte, une crème, pour lui donner une consistance plus ferme.",
	"rafraîchir": "refroidir rapidement un aliment dans de l’eau glacée ou sous un filet d’eau froide.",
	"ragoût à blanc": "mode de cuisson des viandes, volailles, gibiers, coupés en cubes ou découpés en morceaux, qu'on fait d'abord revenir, avec ou sans coloration selon les recettes, et qu'on cuit ensuite dans un liquide aromatisé qui couvre la viande (eau, bouillon, fond, vin). selon que la viande est colorée ou non en début de cuisson, le ragoût est brun ou blanc. le mode de liaison change alors: farine grillée pour les ragoûts bruns, crème et jaunes d'oeufs pour les ragoûts blancs. on ajoute souvent à la cuisson d'un ragoût des légumes (pomme de terre, carotte, navet, oignon, champignon). la cuisson d'un ragoût est toujours lente et à couvert.",
	"ragoût à brun": "mode de cuisson des viandes, volailles, gibiers, coupés en cubes ou découpés en morceaux, qu'on fait d'abord revenir, avec ou sans coloration selon les recettes, et qu'on cuit ensuite dans un liquide aromatisé qui couvre la viande (eau, bouillon, fond, vin). selon que la viande est colorée ou non en début de cuisson, le ragoût est brun ou blanc. le mode de liaison change alors: farine grillée pour les ragoûts bruns, crème et jaunes d'oeufs pour les ragoûts blancs. on ajoute souvent à la cuisson d'un ragoût des légumes (pomme de terre, carotte, navet, oignon, champignon). la cuisson d'un ragoût est toujours lente et à couvert.",
	"raidir": "sauter un aliment dans un corps gras sans coloration, juste pour raidir les chairs.",
	"réduire": "faire bouillir un liquide (sauce, jus) pour en concentrer les saveurs par évaporation de l’eau.",
	"régénérer": "remettre à température un plat sans en modifier l’aspect et la saveur.",
	"relever": "rehausser la saveur d’un met ou d’une préparation en ajoutant des épices ou condiments.",
	"revenir": "colorer un aliment dans un corps gras très chaud.",
	"rissoler": "1. colorer un aliment dans un corps gras très chaud.  2. cuire des pommes de terre suivant la même technique.",
	"rognures": "parures de pâte feuilletée récupérées après le détail de différentes pièces. elles sont utilisées pour réaliser des fleurons ou autres petites pièces de feuilletage.",
	"rompre": "arrêter momentanément la fermentation d’une pâte levée.",
	"rôtir": "cuire une pièce entière dans un four ou à la broche avec un peu de matière grasse sans adjonction de liquide.",
	"rouelle": "tranche épaisse de gigot, jarret de veau, jambon, etc.",
	"roux": "élément de liaison composé en parties égales de beurre et de farine; suivant son temps de cuisson et la couleur de la sauce à lier, il sera « blanc », « blond », « brun ».",
	"ruban": "travailler un appareil à génoise ou une pâte à biscuit jusqu’à obtenir une consistance qui forme un cordon épais en retombant.",
	"russe": "synonyme de casserole",
	"saisir": "exposer un aliment à une température très élevée.",
	"salpicon": "aliments (volailles, viandes, abats, poissons, crustacés, légumes, etc.) coupés en petits dés et liés avec une sauce.",
	"sangler": "versé un appareil à crème glacé ou à sorbet dans une sorbetière pour le congeler.",
	"sauter": "cuire rapidement et à feu vif des petites pièces de viande, volaille, poisson, légumes, etc. dans un récipient avec un peu de matière grasse.",
	"selle anglaise": "c'est ce que les bouchers appellent également la \"selle filet\". morceau de viande pris entre le gigot et la première côte.",
	"serrer": "donner une consistance plus homogène et plus ferme en fouettant d’un mouvement circulaire, à une crème ou des blancs montés.",
	"singer": "saupoudrer de farine des morceaux de viande pour en assurer la liaison (ragoût).",
	"sucs": "protéines et glucides caramélisés au fond du récipient de cuisson. ils sont déglacés par adjonction d’un liquide pour élaborer un jus ou une sauce.",
	"suer": "chauffer doucement un légume dans un corps gras sans coloration.",
	"suprême": "partie charnue de l’aile d’une volaille (le blanc) ou escalope de filet d’un gros poisson (barbue, turbot, etc.)",
	"tamiser": "passer une denrée au travers d’un tamis pour éliminer les grumeaux ou obtenir une texture plus fine.",
	"tamponner": "beurrer la surface d’une préparation afin d’éviter la formation d’une peau (potage, crème, sauce).",
	"torréfier": "colorer la farine à sec au four pour pouvoir singer des morceaux de viande cuits en ragoût à brun.",
	"tourer": "abaisser une pâte feuilletée ou à croissant et la plier plusieurs fois.",
	"tourner": "1. donner une forme régulière et oblongue à certains légumes pour améliorer la présentation et faciliter la cuisson. 2. se dit d’une sauce émulsionnée dont les éléments se dissocient.",
	"travailler": "mélanger une préparation à la spatule, au fouet, ou au batteur électrique.",
	"tremper": "1. réhydrater des légumes ou des fruits secs dans de l’eau froide. 2. imbiber de sirop des babas ou des savarins.",
	"tronçon": "morceaux plus long que large taillé dans un gros poisson plat.",
	"trousser": "inciser les flancs (sous le bréchet) d’une volaille afin d’y introduire l’extrémité de chaque pilon pour qu’ils soient bien maitenus lors du bridage.",
	"turbiner": "versé un appareil à crème glacé ou à sorbet dans une sorbetière pour le congeler.",
	"vanner": "remuer une préparation à la spatule pour favoriser son refroidissement (crème anglaise) et pour éviter la formation d’une peau en surface.",
	"venaison": "terme général désignant le gros gibier (sanglier, cerf, biche, etc.)",
	"videler": "replier les bords d’une abaisse de pâte.",
	"voiler": "recouvrir une pièce de pâtisserie d’un voile de sucre filé.",
	"zeste": "partie colorée de l’écorce odorante des agrumes, prélevée avec un économe ou un zesteur."
};